

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tA_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tA_1_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tA_2_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tA_3_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tB_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tB_1_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tB_2_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tB_3_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tC_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tC_1_U"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tC_2_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tC_3_U"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_init_i_init_j_fu_299"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_init_i_init_j_fu_299.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_load_a_VITIS_LOOP_27_1_fu_307"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_load_a_VITIS_LOOP_27_1_fu_307.mul_5ns_32s_37_1_1_U5"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_load_a_VITIS_LOOP_27_1_fu_307.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_load_b_VITIS_LOOP_30_2_fu_321"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_load_b_VITIS_LOOP_30_2_fu_321.mul_5ns_32s_36_1_1_U16"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_load_b_VITIS_LOOP_30_2_fu_321.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_store_i_store_j_fu_335"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_store_i_store_j_fu_335.mul_5ns_32s_37_1_1_U44"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_store_i_store_j_fu_335.sparsemux_9_2_32_1_1_U45"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_store_i_store_j_fu_335.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_comp_k_fu_349"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_comp_k_fu_349.mul_32s_32s_32_1_1_U27"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_comp_k_fu_349.sparsemux_9_2_32_1_1_U28"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_comp_k_fu_349.sparsemux_9_2_32_1_1_U29"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_mmult_hw_Pipeline_comp_k_fu_349.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.CTRL_s_axi_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_3ns_32s_35_1_1_U55"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_3ns_32s_35_1_1_U56"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_32_1_1_U57"}]}
set DependenceCheckSize 0
