// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dct_dct_Pipeline_WR_Loop_Row (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        sext_ln77,
        buf_2d_out_address0,
        buf_2d_out_ce0,
        buf_2d_out_q0,
        buf_2d_out_1_address0,
        buf_2d_out_1_ce0,
        buf_2d_out_1_q0,
        buf_2d_out_2_address0,
        buf_2d_out_2_ce0,
        buf_2d_out_2_q0,
        buf_2d_out_3_address0,
        buf_2d_out_3_ce0,
        buf_2d_out_3_q0,
        buf_2d_out_4_address0,
        buf_2d_out_4_ce0,
        buf_2d_out_4_q0,
        buf_2d_out_5_address0,
        buf_2d_out_5_ce0,
        buf_2d_out_5_q0,
        buf_2d_out_6_address0,
        buf_2d_out_6_ce0,
        buf_2d_out_6_q0,
        buf_2d_out_7_address0,
        buf_2d_out_7_ce0,
        buf_2d_out_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [511:0] m_axi_gmem_WDATA;
output  [63:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [511:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [57:0] sext_ln77;
output  [2:0] buf_2d_out_address0;
output   buf_2d_out_ce0;
input  [15:0] buf_2d_out_q0;
output  [2:0] buf_2d_out_1_address0;
output   buf_2d_out_1_ce0;
input  [15:0] buf_2d_out_1_q0;
output  [2:0] buf_2d_out_2_address0;
output   buf_2d_out_2_ce0;
input  [15:0] buf_2d_out_2_q0;
output  [2:0] buf_2d_out_3_address0;
output   buf_2d_out_3_ce0;
input  [15:0] buf_2d_out_3_q0;
output  [2:0] buf_2d_out_4_address0;
output   buf_2d_out_4_ce0;
input  [15:0] buf_2d_out_4_q0;
output  [2:0] buf_2d_out_5_address0;
output   buf_2d_out_5_ce0;
input  [15:0] buf_2d_out_5_q0;
output  [2:0] buf_2d_out_6_address0;
output   buf_2d_out_6_ce0;
input  [15:0] buf_2d_out_6_q0;
output  [2:0] buf_2d_out_7_address0;
output   buf_2d_out_7_ce0;
input  [15:0] buf_2d_out_7_q0;

reg ap_idle;
reg m_axi_gmem_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln77_1_reg_389;
reg   [0:0] icmp_ln77_1_reg_389_pp0_iter1_reg;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln77_fu_223_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_W;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln77_1_fu_251_p2;
reg   [15:0] buf_2d_out_load_reg_394;
reg   [15:0] buf_2d_out_1_load_reg_400;
reg   [15:0] buf_2d_out_2_load_reg_406;
reg   [15:0] buf_2d_out_3_load_reg_412;
reg   [15:0] buf_2d_out_4_load_reg_418;
reg   [15:0] buf_2d_out_5_load_reg_424;
reg   [15:0] buf_2d_out_6_load_reg_430;
reg   [15:0] buf_2d_out_7_load_reg_436;
wire   [63:0] zext_ln77_fu_235_p1;
wire    ap_block_pp0_stage0_01001;
reg   [383:0] phi_ln77_fu_80;
wire   [383:0] select_ln77_fu_313_p3;
wire    ap_loop_init;
reg   [3:0] r_fu_84;
wire   [3:0] add_ln77_fu_229_p2;
reg   [3:0] ap_sig_allocacmp_r_1;
reg    buf_2d_out_ce0_local;
reg    buf_2d_out_1_ce0_local;
reg    buf_2d_out_2_ce0_local;
reg    buf_2d_out_3_ce0_local;
reg    buf_2d_out_4_ce0_local;
reg    buf_2d_out_5_ce0_local;
reg    buf_2d_out_6_ce0_local;
reg    buf_2d_out_7_ce0_local;
wire   [1:0] trunc_ln77_fu_247_p1;
wire   [255:0] tmp_fu_289_p4;
wire   [383:0] tmp_8_fu_299_p10;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 phi_ln77_fu_80 = 384'd0;
#0 r_fu_84 = 4'd0;
#0 ap_done_reg = 1'b0;
end

dct_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_ln77_fu_80 <= 384'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            phi_ln77_fu_80 <= select_ln77_fu_313_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln77_fu_223_p2 == 1'd0))) begin
            r_fu_84 <= add_ln77_fu_229_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_84 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        buf_2d_out_1_load_reg_400 <= buf_2d_out_1_q0;
        buf_2d_out_2_load_reg_406 <= buf_2d_out_2_q0;
        buf_2d_out_3_load_reg_412 <= buf_2d_out_3_q0;
        buf_2d_out_4_load_reg_418 <= buf_2d_out_4_q0;
        buf_2d_out_5_load_reg_424 <= buf_2d_out_5_q0;
        buf_2d_out_6_load_reg_430 <= buf_2d_out_6_q0;
        buf_2d_out_7_load_reg_436 <= buf_2d_out_7_q0;
        buf_2d_out_load_reg_394 <= buf_2d_out_q0;
        icmp_ln77_1_reg_389 <= icmp_ln77_1_fu_251_p2;
        icmp_ln77_1_reg_389_pp0_iter1_reg <= icmp_ln77_1_reg_389;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln77_fu_223_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_r_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_r_1 = r_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_2d_out_1_ce0_local = 1'b1;
    end else begin
        buf_2d_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_2d_out_2_ce0_local = 1'b1;
    end else begin
        buf_2d_out_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_2d_out_3_ce0_local = 1'b1;
    end else begin
        buf_2d_out_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_2d_out_4_ce0_local = 1'b1;
    end else begin
        buf_2d_out_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_2d_out_5_ce0_local = 1'b1;
    end else begin
        buf_2d_out_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_2d_out_6_ce0_local = 1'b1;
    end else begin
        buf_2d_out_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_2d_out_7_ce0_local = 1'b1;
    end else begin
        buf_2d_out_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_2d_out_ce0_local = 1'b1;
    end else begin
        buf_2d_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln77_1_reg_389_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln77_1_reg_389_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln77_fu_229_p2 = (ap_sig_allocacmp_r_1 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io));
end

always @ (*) begin
    ap_block_state3_io = ((icmp_ln77_1_reg_389_pp0_iter1_reg == 1'd1) & (m_axi_gmem_WREADY == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buf_2d_out_1_address0 = zext_ln77_fu_235_p1;

assign buf_2d_out_1_ce0 = buf_2d_out_1_ce0_local;

assign buf_2d_out_2_address0 = zext_ln77_fu_235_p1;

assign buf_2d_out_2_ce0 = buf_2d_out_2_ce0_local;

assign buf_2d_out_3_address0 = zext_ln77_fu_235_p1;

assign buf_2d_out_3_ce0 = buf_2d_out_3_ce0_local;

assign buf_2d_out_4_address0 = zext_ln77_fu_235_p1;

assign buf_2d_out_4_ce0 = buf_2d_out_4_ce0_local;

assign buf_2d_out_5_address0 = zext_ln77_fu_235_p1;

assign buf_2d_out_5_ce0 = buf_2d_out_5_ce0_local;

assign buf_2d_out_6_address0 = zext_ln77_fu_235_p1;

assign buf_2d_out_6_ce0 = buf_2d_out_6_ce0_local;

assign buf_2d_out_7_address0 = zext_ln77_fu_235_p1;

assign buf_2d_out_7_ce0 = buf_2d_out_7_ce0_local;

assign buf_2d_out_address0 = zext_ln77_fu_235_p1;

assign buf_2d_out_ce0 = buf_2d_out_ce0_local;

assign icmp_ln77_1_fu_251_p2 = ((trunc_ln77_fu_247_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_223_p2 = ((ap_sig_allocacmp_r_1 == 4'd8) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = 64'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_RREADY = 1'b0;

assign m_axi_gmem_WDATA = {{{{{{{{{buf_2d_out_7_load_reg_436}, {buf_2d_out_6_load_reg_430}}, {buf_2d_out_5_load_reg_424}}, {buf_2d_out_4_load_reg_418}}, {buf_2d_out_3_load_reg_412}}, {buf_2d_out_2_load_reg_406}}, {buf_2d_out_1_load_reg_400}}, {buf_2d_out_load_reg_394}}, {phi_ln77_fu_80}};

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 64'd18446744073709551615;

assign m_axi_gmem_WUSER = 1'd0;

assign select_ln77_fu_313_p3 = ((icmp_ln77_1_reg_389_pp0_iter1_reg[0:0] == 1'b1) ? 384'd0 : tmp_8_fu_299_p10);

assign tmp_8_fu_299_p10 = {{{{{{{{{buf_2d_out_7_load_reg_436}, {buf_2d_out_6_load_reg_430}}, {buf_2d_out_5_load_reg_424}}, {buf_2d_out_4_load_reg_418}}, {buf_2d_out_3_load_reg_412}}, {buf_2d_out_2_load_reg_406}}, {buf_2d_out_1_load_reg_400}}, {buf_2d_out_load_reg_394}}, {tmp_fu_289_p4}};

assign tmp_fu_289_p4 = {{phi_ln77_fu_80[383:128]}};

assign trunc_ln77_fu_247_p1 = ap_sig_allocacmp_r_1[1:0];

assign zext_ln77_fu_235_p1 = ap_sig_allocacmp_r_1;

endmodule //dct_dct_Pipeline_WR_Loop_Row
