# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/GitRepos/EECE4632/HW4/Vivado/divby13_stream/divby13_stream.srcs/sources_1/bd/divby13_stream/ip/divby13_stream_axi_dma_1/divby13_stream_axi_dma_1.xci
# IP: The module: 'divby13_stream_axi_dma_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitRepos/EECE4632/HW4/Vivado/divby13_stream/divby13_stream.gen/sources_1/bd/divby13_stream/ip/divby13_stream_axi_dma_1/divby13_stream_axi_dma_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_stream_axi_dma_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/GitRepos/EECE4632/HW4/Vivado/divby13_stream/divby13_stream.gen/sources_1/bd/divby13_stream/ip/divby13_stream_axi_dma_1/divby13_stream_axi_dma_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_stream_axi_dma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/GitRepos/EECE4632/HW4/Vivado/divby13_stream/divby13_stream.gen/sources_1/bd/divby13_stream/ip/divby13_stream_axi_dma_1/divby13_stream_axi_dma_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_stream_axi_dma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/GitRepos/EECE4632/HW4/Vivado/divby13_stream/divby13_stream.srcs/sources_1/bd/divby13_stream/ip/divby13_stream_axi_dma_1/divby13_stream_axi_dma_1.xci
# IP: The module: 'divby13_stream_axi_dma_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitRepos/EECE4632/HW4/Vivado/divby13_stream/divby13_stream.gen/sources_1/bd/divby13_stream/ip/divby13_stream_axi_dma_1/divby13_stream_axi_dma_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_stream_axi_dma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/GitRepos/EECE4632/HW4/Vivado/divby13_stream/divby13_stream.gen/sources_1/bd/divby13_stream/ip/divby13_stream_axi_dma_1/divby13_stream_axi_dma_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_stream_axi_dma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/GitRepos/EECE4632/HW4/Vivado/divby13_stream/divby13_stream.gen/sources_1/bd/divby13_stream/ip/divby13_stream_axi_dma_1/divby13_stream_axi_dma_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_stream_axi_dma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
