# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tran.timo/lab2/lab2.srcs/sources_1/bd/block_1/ip/block_1_add_0_0/block_1_add_0_0.xci
# IP: The module: 'block_1_add_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tran.timo/lab2/lab2.gen/sources_1/bd/block_1/ip/block_1_add_0_0/constraints/add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_1_add_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/tran.timo/lab2/lab2.srcs/sources_1/bd/block_1/ip/block_1_add_0_0/block_1_add_0_0.xci
# IP: The module: 'block_1_add_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tran.timo/lab2/lab2.gen/sources_1/bd/block_1/ip/block_1_add_0_0/constraints/add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_1_add_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
