// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="divby13_stream_divby13_stream,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sfvc784-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.739000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2594,HLS_SYN_LUT=1930,HLS_VERSION=2024_1}" *)

module divby13_stream (
        ap_clk,
        ap_rst_n,
        a_TVALID,
        result_TREADY,
        a_TDATA,
        a_TREADY,
        a_TKEEP,
        a_TSTRB,
        a_TLAST,
        result_TDATA,
        result_TVALID,
        result_TKEEP,
        result_TSTRB,
        result_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   a_TVALID;
input   result_TREADY;
input  [31:0] a_TDATA;
output   a_TREADY;
input  [3:0] a_TKEEP;
input  [3:0] a_TSTRB;
input  [0:0] a_TLAST;
output  [31:0] result_TDATA;
output   result_TVALID;
output  [3:0] result_TKEEP;
output  [3:0] result_TSTRB;
output  [0:0] result_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_idle_pp0;
wire    ap_ready;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state36_pp0_stage0_iter35;
wire    regslice_both_result_V_data_V_U_apdone_blk;
reg    ap_block_state37_pp0_stage0_iter36;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_last_fu_102_p1;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    a_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    result_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] tmp_keep_reg_132;
reg   [3:0] tmp_keep_reg_132_pp0_iter1_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter2_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter3_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter4_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter5_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter6_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter7_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter8_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter9_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter10_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter11_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter12_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter13_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter14_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter15_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter16_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter17_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter18_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter19_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter20_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter21_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter22_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter23_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter24_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter25_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter26_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter27_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter28_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter29_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter30_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter31_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter32_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter33_reg;
reg   [3:0] tmp_keep_reg_132_pp0_iter34_reg;
reg   [3:0] tmp_strb_reg_137;
reg   [3:0] tmp_strb_reg_137_pp0_iter1_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter2_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter3_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter4_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter5_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter6_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter7_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter8_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter9_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter10_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter11_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter12_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter13_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter14_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter15_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter16_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter17_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter18_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter19_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter20_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter21_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter22_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter23_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter24_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter25_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter26_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter27_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter28_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter29_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter30_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter31_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter32_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter33_reg;
reg   [3:0] tmp_strb_reg_137_pp0_iter34_reg;
reg   [0:0] tmp_last_reg_142;
reg   [0:0] tmp_last_reg_142_pp0_iter1_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter2_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter3_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter4_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter5_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter6_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter7_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter8_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter9_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter10_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter11_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter12_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter13_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter14_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter15_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter16_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter17_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter18_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter19_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter20_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter21_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter22_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter23_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter24_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter25_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter26_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter27_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter28_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter29_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter30_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter31_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter32_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter33_reg;
reg   [0:0] tmp_last_reg_142_pp0_iter34_reg;
reg    ap_block_pp0_stage0_01001;
wire   [4:0] grp_fu_106_p1;
wire   [4:0] grp_fu_106_p2;
wire   [4:0] trunc_ln16_fu_112_p1;
wire   [0:0] res_fu_116_p2;
reg    grp_fu_106_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_loop_init;
wire    regslice_both_a_V_data_V_U_apdone_blk;
wire   [31:0] a_TDATA_int_regslice;
wire    a_TVALID_int_regslice;
reg    a_TREADY_int_regslice;
wire    regslice_both_a_V_data_V_U_ack_in;
wire    regslice_both_a_V_keep_V_U_apdone_blk;
wire   [3:0] a_TKEEP_int_regslice;
wire    regslice_both_a_V_keep_V_U_vld_out;
wire    regslice_both_a_V_keep_V_U_ack_in;
wire    regslice_both_a_V_strb_V_U_apdone_blk;
wire   [3:0] a_TSTRB_int_regslice;
wire    regslice_both_a_V_strb_V_U_vld_out;
wire    regslice_both_a_V_strb_V_U_ack_in;
wire    regslice_both_a_V_last_V_U_apdone_blk;
wire   [0:0] a_TLAST_int_regslice;
wire    regslice_both_a_V_last_V_U_vld_out;
wire    regslice_both_a_V_last_V_U_ack_in;
wire   [31:0] result_TDATA_int_regslice;
reg    result_TVALID_int_regslice;
wire    result_TREADY_int_regslice;
wire    regslice_both_result_V_data_V_U_vld_out;
wire    regslice_both_result_V_keep_V_U_apdone_blk;
wire    regslice_both_result_V_keep_V_U_ack_in_dummy;
wire    regslice_both_result_V_keep_V_U_vld_out;
wire    regslice_both_result_V_strb_V_U_apdone_blk;
wire    regslice_both_result_V_strb_V_U_ack_in_dummy;
wire    regslice_both_result_V_strb_V_U_vld_out;
wire    regslice_both_result_V_last_V_U_apdone_blk;
wire    regslice_both_result_V_last_V_U_ack_in_dummy;
wire    regslice_both_result_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_done_reg = 1'b0;
end

divby13_stream_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

divby13_stream_srem_32ns_5ns_5_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 5 ))
srem_32ns_5ns_5_36_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(a_TDATA_int_regslice),
    .din1(grp_fu_106_p1),
    .ce(grp_fu_106_ce),
    .dout(grp_fu_106_p2)
);

divby13_stream_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

divby13_stream_regslice_both #(
    .DataWidth( 32 ))
regslice_both_a_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(a_TDATA),
    .vld_in(a_TVALID),
    .ack_in(regslice_both_a_V_data_V_U_ack_in),
    .data_out(a_TDATA_int_regslice),
    .vld_out(a_TVALID_int_regslice),
    .ack_out(a_TREADY_int_regslice),
    .apdone_blk(regslice_both_a_V_data_V_U_apdone_blk)
);

divby13_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_a_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(a_TKEEP),
    .vld_in(a_TVALID),
    .ack_in(regslice_both_a_V_keep_V_U_ack_in),
    .data_out(a_TKEEP_int_regslice),
    .vld_out(regslice_both_a_V_keep_V_U_vld_out),
    .ack_out(a_TREADY_int_regslice),
    .apdone_blk(regslice_both_a_V_keep_V_U_apdone_blk)
);

divby13_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_a_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(a_TSTRB),
    .vld_in(a_TVALID),
    .ack_in(regslice_both_a_V_strb_V_U_ack_in),
    .data_out(a_TSTRB_int_regslice),
    .vld_out(regslice_both_a_V_strb_V_U_vld_out),
    .ack_out(a_TREADY_int_regslice),
    .apdone_blk(regslice_both_a_V_strb_V_U_apdone_blk)
);

divby13_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_a_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(a_TLAST),
    .vld_in(a_TVALID),
    .ack_in(regslice_both_a_V_last_V_U_ack_in),
    .data_out(a_TLAST_int_regslice),
    .vld_out(regslice_both_a_V_last_V_U_vld_out),
    .ack_out(a_TREADY_int_regslice),
    .apdone_blk(regslice_both_a_V_last_V_U_apdone_blk)
);

divby13_stream_regslice_both #(
    .DataWidth( 32 ))
regslice_both_result_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(result_TDATA_int_regslice),
    .vld_in(result_TVALID_int_regslice),
    .ack_in(result_TREADY_int_regslice),
    .data_out(result_TDATA),
    .vld_out(regslice_both_result_V_data_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_data_V_U_apdone_blk)
);

divby13_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_result_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_keep_reg_132_pp0_iter34_reg),
    .vld_in(result_TVALID_int_regslice),
    .ack_in(regslice_both_result_V_keep_V_U_ack_in_dummy),
    .data_out(result_TKEEP),
    .vld_out(regslice_both_result_V_keep_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_keep_V_U_apdone_blk)
);

divby13_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_result_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_strb_reg_137_pp0_iter34_reg),
    .vld_in(result_TVALID_int_regslice),
    .ack_in(regslice_both_result_V_strb_V_U_ack_in_dummy),
    .data_out(result_TSTRB),
    .vld_out(regslice_both_result_V_strb_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_strb_V_U_apdone_blk)
);

divby13_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_result_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_last_reg_142_pp0_iter34_reg),
    .vld_in(result_TVALID_int_regslice),
    .ack_in(regslice_both_result_V_last_V_U_ack_in_dummy),
    .data_out(result_TLAST),
    .vld_out(regslice_both_result_V_last_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter36_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter35_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter36_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        tmp_keep_reg_132_pp0_iter10_reg <= tmp_keep_reg_132_pp0_iter9_reg;
        tmp_keep_reg_132_pp0_iter11_reg <= tmp_keep_reg_132_pp0_iter10_reg;
        tmp_keep_reg_132_pp0_iter12_reg <= tmp_keep_reg_132_pp0_iter11_reg;
        tmp_keep_reg_132_pp0_iter13_reg <= tmp_keep_reg_132_pp0_iter12_reg;
        tmp_keep_reg_132_pp0_iter14_reg <= tmp_keep_reg_132_pp0_iter13_reg;
        tmp_keep_reg_132_pp0_iter15_reg <= tmp_keep_reg_132_pp0_iter14_reg;
        tmp_keep_reg_132_pp0_iter16_reg <= tmp_keep_reg_132_pp0_iter15_reg;
        tmp_keep_reg_132_pp0_iter17_reg <= tmp_keep_reg_132_pp0_iter16_reg;
        tmp_keep_reg_132_pp0_iter18_reg <= tmp_keep_reg_132_pp0_iter17_reg;
        tmp_keep_reg_132_pp0_iter19_reg <= tmp_keep_reg_132_pp0_iter18_reg;
        tmp_keep_reg_132_pp0_iter20_reg <= tmp_keep_reg_132_pp0_iter19_reg;
        tmp_keep_reg_132_pp0_iter21_reg <= tmp_keep_reg_132_pp0_iter20_reg;
        tmp_keep_reg_132_pp0_iter22_reg <= tmp_keep_reg_132_pp0_iter21_reg;
        tmp_keep_reg_132_pp0_iter23_reg <= tmp_keep_reg_132_pp0_iter22_reg;
        tmp_keep_reg_132_pp0_iter24_reg <= tmp_keep_reg_132_pp0_iter23_reg;
        tmp_keep_reg_132_pp0_iter25_reg <= tmp_keep_reg_132_pp0_iter24_reg;
        tmp_keep_reg_132_pp0_iter26_reg <= tmp_keep_reg_132_pp0_iter25_reg;
        tmp_keep_reg_132_pp0_iter27_reg <= tmp_keep_reg_132_pp0_iter26_reg;
        tmp_keep_reg_132_pp0_iter28_reg <= tmp_keep_reg_132_pp0_iter27_reg;
        tmp_keep_reg_132_pp0_iter29_reg <= tmp_keep_reg_132_pp0_iter28_reg;
        tmp_keep_reg_132_pp0_iter2_reg <= tmp_keep_reg_132_pp0_iter1_reg;
        tmp_keep_reg_132_pp0_iter30_reg <= tmp_keep_reg_132_pp0_iter29_reg;
        tmp_keep_reg_132_pp0_iter31_reg <= tmp_keep_reg_132_pp0_iter30_reg;
        tmp_keep_reg_132_pp0_iter32_reg <= tmp_keep_reg_132_pp0_iter31_reg;
        tmp_keep_reg_132_pp0_iter33_reg <= tmp_keep_reg_132_pp0_iter32_reg;
        tmp_keep_reg_132_pp0_iter34_reg <= tmp_keep_reg_132_pp0_iter33_reg;
        tmp_keep_reg_132_pp0_iter3_reg <= tmp_keep_reg_132_pp0_iter2_reg;
        tmp_keep_reg_132_pp0_iter4_reg <= tmp_keep_reg_132_pp0_iter3_reg;
        tmp_keep_reg_132_pp0_iter5_reg <= tmp_keep_reg_132_pp0_iter4_reg;
        tmp_keep_reg_132_pp0_iter6_reg <= tmp_keep_reg_132_pp0_iter5_reg;
        tmp_keep_reg_132_pp0_iter7_reg <= tmp_keep_reg_132_pp0_iter6_reg;
        tmp_keep_reg_132_pp0_iter8_reg <= tmp_keep_reg_132_pp0_iter7_reg;
        tmp_keep_reg_132_pp0_iter9_reg <= tmp_keep_reg_132_pp0_iter8_reg;
        tmp_last_reg_142_pp0_iter10_reg <= tmp_last_reg_142_pp0_iter9_reg;
        tmp_last_reg_142_pp0_iter11_reg <= tmp_last_reg_142_pp0_iter10_reg;
        tmp_last_reg_142_pp0_iter12_reg <= tmp_last_reg_142_pp0_iter11_reg;
        tmp_last_reg_142_pp0_iter13_reg <= tmp_last_reg_142_pp0_iter12_reg;
        tmp_last_reg_142_pp0_iter14_reg <= tmp_last_reg_142_pp0_iter13_reg;
        tmp_last_reg_142_pp0_iter15_reg <= tmp_last_reg_142_pp0_iter14_reg;
        tmp_last_reg_142_pp0_iter16_reg <= tmp_last_reg_142_pp0_iter15_reg;
        tmp_last_reg_142_pp0_iter17_reg <= tmp_last_reg_142_pp0_iter16_reg;
        tmp_last_reg_142_pp0_iter18_reg <= tmp_last_reg_142_pp0_iter17_reg;
        tmp_last_reg_142_pp0_iter19_reg <= tmp_last_reg_142_pp0_iter18_reg;
        tmp_last_reg_142_pp0_iter20_reg <= tmp_last_reg_142_pp0_iter19_reg;
        tmp_last_reg_142_pp0_iter21_reg <= tmp_last_reg_142_pp0_iter20_reg;
        tmp_last_reg_142_pp0_iter22_reg <= tmp_last_reg_142_pp0_iter21_reg;
        tmp_last_reg_142_pp0_iter23_reg <= tmp_last_reg_142_pp0_iter22_reg;
        tmp_last_reg_142_pp0_iter24_reg <= tmp_last_reg_142_pp0_iter23_reg;
        tmp_last_reg_142_pp0_iter25_reg <= tmp_last_reg_142_pp0_iter24_reg;
        tmp_last_reg_142_pp0_iter26_reg <= tmp_last_reg_142_pp0_iter25_reg;
        tmp_last_reg_142_pp0_iter27_reg <= tmp_last_reg_142_pp0_iter26_reg;
        tmp_last_reg_142_pp0_iter28_reg <= tmp_last_reg_142_pp0_iter27_reg;
        tmp_last_reg_142_pp0_iter29_reg <= tmp_last_reg_142_pp0_iter28_reg;
        tmp_last_reg_142_pp0_iter2_reg <= tmp_last_reg_142_pp0_iter1_reg;
        tmp_last_reg_142_pp0_iter30_reg <= tmp_last_reg_142_pp0_iter29_reg;
        tmp_last_reg_142_pp0_iter31_reg <= tmp_last_reg_142_pp0_iter30_reg;
        tmp_last_reg_142_pp0_iter32_reg <= tmp_last_reg_142_pp0_iter31_reg;
        tmp_last_reg_142_pp0_iter33_reg <= tmp_last_reg_142_pp0_iter32_reg;
        tmp_last_reg_142_pp0_iter34_reg <= tmp_last_reg_142_pp0_iter33_reg;
        tmp_last_reg_142_pp0_iter3_reg <= tmp_last_reg_142_pp0_iter2_reg;
        tmp_last_reg_142_pp0_iter4_reg <= tmp_last_reg_142_pp0_iter3_reg;
        tmp_last_reg_142_pp0_iter5_reg <= tmp_last_reg_142_pp0_iter4_reg;
        tmp_last_reg_142_pp0_iter6_reg <= tmp_last_reg_142_pp0_iter5_reg;
        tmp_last_reg_142_pp0_iter7_reg <= tmp_last_reg_142_pp0_iter6_reg;
        tmp_last_reg_142_pp0_iter8_reg <= tmp_last_reg_142_pp0_iter7_reg;
        tmp_last_reg_142_pp0_iter9_reg <= tmp_last_reg_142_pp0_iter8_reg;
        tmp_strb_reg_137_pp0_iter10_reg <= tmp_strb_reg_137_pp0_iter9_reg;
        tmp_strb_reg_137_pp0_iter11_reg <= tmp_strb_reg_137_pp0_iter10_reg;
        tmp_strb_reg_137_pp0_iter12_reg <= tmp_strb_reg_137_pp0_iter11_reg;
        tmp_strb_reg_137_pp0_iter13_reg <= tmp_strb_reg_137_pp0_iter12_reg;
        tmp_strb_reg_137_pp0_iter14_reg <= tmp_strb_reg_137_pp0_iter13_reg;
        tmp_strb_reg_137_pp0_iter15_reg <= tmp_strb_reg_137_pp0_iter14_reg;
        tmp_strb_reg_137_pp0_iter16_reg <= tmp_strb_reg_137_pp0_iter15_reg;
        tmp_strb_reg_137_pp0_iter17_reg <= tmp_strb_reg_137_pp0_iter16_reg;
        tmp_strb_reg_137_pp0_iter18_reg <= tmp_strb_reg_137_pp0_iter17_reg;
        tmp_strb_reg_137_pp0_iter19_reg <= tmp_strb_reg_137_pp0_iter18_reg;
        tmp_strb_reg_137_pp0_iter20_reg <= tmp_strb_reg_137_pp0_iter19_reg;
        tmp_strb_reg_137_pp0_iter21_reg <= tmp_strb_reg_137_pp0_iter20_reg;
        tmp_strb_reg_137_pp0_iter22_reg <= tmp_strb_reg_137_pp0_iter21_reg;
        tmp_strb_reg_137_pp0_iter23_reg <= tmp_strb_reg_137_pp0_iter22_reg;
        tmp_strb_reg_137_pp0_iter24_reg <= tmp_strb_reg_137_pp0_iter23_reg;
        tmp_strb_reg_137_pp0_iter25_reg <= tmp_strb_reg_137_pp0_iter24_reg;
        tmp_strb_reg_137_pp0_iter26_reg <= tmp_strb_reg_137_pp0_iter25_reg;
        tmp_strb_reg_137_pp0_iter27_reg <= tmp_strb_reg_137_pp0_iter26_reg;
        tmp_strb_reg_137_pp0_iter28_reg <= tmp_strb_reg_137_pp0_iter27_reg;
        tmp_strb_reg_137_pp0_iter29_reg <= tmp_strb_reg_137_pp0_iter28_reg;
        tmp_strb_reg_137_pp0_iter2_reg <= tmp_strb_reg_137_pp0_iter1_reg;
        tmp_strb_reg_137_pp0_iter30_reg <= tmp_strb_reg_137_pp0_iter29_reg;
        tmp_strb_reg_137_pp0_iter31_reg <= tmp_strb_reg_137_pp0_iter30_reg;
        tmp_strb_reg_137_pp0_iter32_reg <= tmp_strb_reg_137_pp0_iter31_reg;
        tmp_strb_reg_137_pp0_iter33_reg <= tmp_strb_reg_137_pp0_iter32_reg;
        tmp_strb_reg_137_pp0_iter34_reg <= tmp_strb_reg_137_pp0_iter33_reg;
        tmp_strb_reg_137_pp0_iter3_reg <= tmp_strb_reg_137_pp0_iter2_reg;
        tmp_strb_reg_137_pp0_iter4_reg <= tmp_strb_reg_137_pp0_iter3_reg;
        tmp_strb_reg_137_pp0_iter5_reg <= tmp_strb_reg_137_pp0_iter4_reg;
        tmp_strb_reg_137_pp0_iter6_reg <= tmp_strb_reg_137_pp0_iter5_reg;
        tmp_strb_reg_137_pp0_iter7_reg <= tmp_strb_reg_137_pp0_iter6_reg;
        tmp_strb_reg_137_pp0_iter8_reg <= tmp_strb_reg_137_pp0_iter7_reg;
        tmp_strb_reg_137_pp0_iter9_reg <= tmp_strb_reg_137_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_keep_reg_132 <= a_TKEEP_int_regslice;
        tmp_keep_reg_132_pp0_iter1_reg <= tmp_keep_reg_132;
        tmp_last_reg_142 <= a_TLAST_int_regslice;
        tmp_last_reg_142_pp0_iter1_reg <= tmp_last_reg_142;
        tmp_strb_reg_137 <= a_TSTRB_int_regslice;
        tmp_strb_reg_137_pp0_iter1_reg <= tmp_strb_reg_137;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        a_TDATA_blk_n = a_TVALID_int_regslice;
    end else begin
        a_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        a_TREADY_int_regslice = 1'b1;
    end else begin
        a_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_last_fu_102_p1 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter36_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) 
    & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_106_ce = 1'b1;
    end else begin
        grp_fu_106_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter36 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter35 == 1'b1)))) begin
        result_TDATA_blk_n = result_TREADY_int_regslice;
    end else begin
        result_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        result_TVALID_int_regslice = 1'b1;
    end else begin
        result_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_TREADY = regslice_both_a_V_data_V_U_ack_in;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter36_reg == 1'b1) & (regslice_both_result_V_data_V_U_apdone_blk == 1'b1)) | ((1'b1 == ap_block_state37_pp0_stage0_iter36) & (ap_enable_reg_pp0_iter36 == 1'b1)) | ((1'b1 == ap_block_state36_pp0_stage0_iter35) & (ap_enable_reg_pp0_iter35 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter36_reg == 1'b1) & (regslice_both_result_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter36 == 1'b1) & ((result_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state37_pp0_stage0_iter36))) | ((ap_enable_reg_pp0_iter35 == 1'b1) & ((result_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state36_pp0_stage0_iter35))) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter36_reg == 1'b1) & (regslice_both_result_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter36 == 1'b1) & ((result_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state37_pp0_stage0_iter36))) | ((ap_enable_reg_pp0_iter35 == 1'b1) & ((result_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state36_pp0_stage0_iter35))) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (1'b0 == a_TVALID_int_regslice);
end

always @ (*) begin
    ap_block_state36_pp0_stage0_iter35 = (result_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state37_pp0_stage0_iter36 = ((result_TREADY_int_regslice == 1'b0) | (regslice_both_result_V_data_V_U_apdone_blk == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_106_p1 = 32'd13;

assign res_fu_116_p2 = ((trunc_ln16_fu_112_p1 == 5'd0) ? 1'b1 : 1'b0);

assign result_TDATA_int_regslice = res_fu_116_p2;

assign result_TVALID = regslice_both_result_V_data_V_U_vld_out;

assign tmp_last_fu_102_p1 = a_TLAST_int_regslice;

assign trunc_ln16_fu_112_p1 = grp_fu_106_p2[4:0];


reg find_kernel_block = 0;
// synthesis translate_off
`include "divby13_stream_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //divby13_stream

