# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGAHW/HW3/Vivado/divby13/divby13.srcs/sources_1/bd/divby13/ip/divby13_proc_sys_reset_0_0/divby13_proc_sys_reset_0_0.xci
# IP: The module: 'divby13_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGAHW/HW3/Vivado/divby13/divby13.gen/sources_1/bd/divby13/ip/divby13_proc_sys_reset_0_0/divby13_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGAHW/HW3/Vivado/divby13/divby13.gen/sources_1/bd/divby13/ip/divby13_proc_sys_reset_0_0/divby13_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGAHW/HW3/Vivado/divby13/divby13.gen/sources_1/bd/divby13/ip/divby13_proc_sys_reset_0_0/divby13_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/FPGAHW/HW3/Vivado/divby13/divby13.srcs/sources_1/bd/divby13/ip/divby13_proc_sys_reset_0_0/divby13_proc_sys_reset_0_0.xci
# IP: The module: 'divby13_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGAHW/HW3/Vivado/divby13/divby13.gen/sources_1/bd/divby13/ip/divby13_proc_sys_reset_0_0/divby13_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGAHW/HW3/Vivado/divby13/divby13.gen/sources_1/bd/divby13/ip/divby13_proc_sys_reset_0_0/divby13_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGAHW/HW3/Vivado/divby13/divby13.gen/sources_1/bd/divby13/ip/divby13_proc_sys_reset_0_0/divby13_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divby13_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
