-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity divby13_stream is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    a_TVALID : IN STD_LOGIC;
    result_TREADY : IN STD_LOGIC;
    a_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    a_TREADY : OUT STD_LOGIC;
    a_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    a_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    a_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    result_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    result_TVALID : OUT STD_LOGIC;
    result_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    result_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    result_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of divby13_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "divby13_stream_divby13_stream,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sfvc784-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.739000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2594,HLS_SYN_LUT=1930,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter32 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter33 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter34 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter35 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter36 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state36_pp0_stage0_iter35 : BOOLEAN;
    signal regslice_both_result_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state37_pp0_stage0_iter36 : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter36_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_last_fu_102_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal a_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal result_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_keep_reg_132 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter11_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter12_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter13_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter14_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter15_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter16_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter17_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter18_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter19_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter20_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter21_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter22_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter23_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter24_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter25_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter26_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter27_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter28_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter29_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter30_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter31_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter32_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter33_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_132_pp0_iter34_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter11_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter12_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter13_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter14_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter15_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter16_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter17_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter18_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter19_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter20_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter21_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter22_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter23_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter24_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter25_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter26_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter27_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter28_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter29_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter30_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter31_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter32_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter33_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_137_pp0_iter34_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_last_reg_142 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_142_pp0_iter34_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_106_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_106_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln16_fu_112_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal res_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_106_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter27_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter28_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter29_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter30_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter31_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter32_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter33_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter34_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter35_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal regslice_both_a_V_data_V_U_apdone_blk : STD_LOGIC;
    signal a_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal a_TVALID_int_regslice : STD_LOGIC;
    signal a_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_a_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_a_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal a_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_a_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_a_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_a_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal a_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_a_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_a_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_a_V_last_V_U_apdone_blk : STD_LOGIC;
    signal a_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_a_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_a_V_last_V_U_ack_in : STD_LOGIC;
    signal result_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal result_TVALID_int_regslice : STD_LOGIC;
    signal result_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_result_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_result_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_result_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_result_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_result_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_result_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_result_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_result_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_result_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_result_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component divby13_stream_srem_32ns_5ns_5_36_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component divby13_stream_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component divby13_stream_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component divby13_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    control_s_axi_U : component divby13_stream_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    srem_32ns_5ns_5_36_1_U1 : component divby13_stream_srem_32ns_5ns_5_36_1
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 5,
        dout_WIDTH => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => a_TDATA_int_regslice,
        din1 => grp_fu_106_p1,
        ce => grp_fu_106_ce,
        dout => grp_fu_106_p2);

    flow_control_loop_pipe_U : component divby13_stream_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);

    regslice_both_a_V_data_V_U : component divby13_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => a_TDATA,
        vld_in => a_TVALID,
        ack_in => regslice_both_a_V_data_V_U_ack_in,
        data_out => a_TDATA_int_regslice,
        vld_out => a_TVALID_int_regslice,
        ack_out => a_TREADY_int_regslice,
        apdone_blk => regslice_both_a_V_data_V_U_apdone_blk);

    regslice_both_a_V_keep_V_U : component divby13_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => a_TKEEP,
        vld_in => a_TVALID,
        ack_in => regslice_both_a_V_keep_V_U_ack_in,
        data_out => a_TKEEP_int_regslice,
        vld_out => regslice_both_a_V_keep_V_U_vld_out,
        ack_out => a_TREADY_int_regslice,
        apdone_blk => regslice_both_a_V_keep_V_U_apdone_blk);

    regslice_both_a_V_strb_V_U : component divby13_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => a_TSTRB,
        vld_in => a_TVALID,
        ack_in => regslice_both_a_V_strb_V_U_ack_in,
        data_out => a_TSTRB_int_regslice,
        vld_out => regslice_both_a_V_strb_V_U_vld_out,
        ack_out => a_TREADY_int_regslice,
        apdone_blk => regslice_both_a_V_strb_V_U_apdone_blk);

    regslice_both_a_V_last_V_U : component divby13_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => a_TLAST,
        vld_in => a_TVALID,
        ack_in => regslice_both_a_V_last_V_U_ack_in,
        data_out => a_TLAST_int_regslice,
        vld_out => regslice_both_a_V_last_V_U_vld_out,
        ack_out => a_TREADY_int_regslice,
        apdone_blk => regslice_both_a_V_last_V_U_apdone_blk);

    regslice_both_result_V_data_V_U : component divby13_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => result_TDATA_int_regslice,
        vld_in => result_TVALID_int_regslice,
        ack_in => result_TREADY_int_regslice,
        data_out => result_TDATA,
        vld_out => regslice_both_result_V_data_V_U_vld_out,
        ack_out => result_TREADY,
        apdone_blk => regslice_both_result_V_data_V_U_apdone_blk);

    regslice_both_result_V_keep_V_U : component divby13_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_keep_reg_132_pp0_iter34_reg,
        vld_in => result_TVALID_int_regslice,
        ack_in => regslice_both_result_V_keep_V_U_ack_in_dummy,
        data_out => result_TKEEP,
        vld_out => regslice_both_result_V_keep_V_U_vld_out,
        ack_out => result_TREADY,
        apdone_blk => regslice_both_result_V_keep_V_U_apdone_blk);

    regslice_both_result_V_strb_V_U : component divby13_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_strb_reg_137_pp0_iter34_reg,
        vld_in => result_TVALID_int_regslice,
        ack_in => regslice_both_result_V_strb_V_U_ack_in_dummy,
        data_out => result_TSTRB,
        vld_out => regslice_both_result_V_strb_V_U_vld_out,
        ack_out => result_TREADY,
        apdone_blk => regslice_both_result_V_strb_V_U_apdone_blk);

    regslice_both_result_V_last_V_U : component divby13_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_last_reg_142_pp0_iter34_reg,
        vld_in => result_TVALID_int_regslice,
        ack_in => regslice_both_result_V_last_V_U_ack_in_dummy,
        data_out => result_TLAST,
        vld_out => regslice_both_result_V_last_V_U_vld_out,
        ack_out => result_TREADY,
        apdone_blk => regslice_both_result_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter36_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter32_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter33_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter33 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter34_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter34 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter35_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter35 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter36_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter36 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter36_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_exit_ready_pp0_iter35_reg = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                ap_loop_exit_ready_pp0_iter36_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
                ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
                ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
                ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
                ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
                ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
                ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
                ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
                ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                tmp_keep_reg_132_pp0_iter10_reg <= tmp_keep_reg_132_pp0_iter9_reg;
                tmp_keep_reg_132_pp0_iter11_reg <= tmp_keep_reg_132_pp0_iter10_reg;
                tmp_keep_reg_132_pp0_iter12_reg <= tmp_keep_reg_132_pp0_iter11_reg;
                tmp_keep_reg_132_pp0_iter13_reg <= tmp_keep_reg_132_pp0_iter12_reg;
                tmp_keep_reg_132_pp0_iter14_reg <= tmp_keep_reg_132_pp0_iter13_reg;
                tmp_keep_reg_132_pp0_iter15_reg <= tmp_keep_reg_132_pp0_iter14_reg;
                tmp_keep_reg_132_pp0_iter16_reg <= tmp_keep_reg_132_pp0_iter15_reg;
                tmp_keep_reg_132_pp0_iter17_reg <= tmp_keep_reg_132_pp0_iter16_reg;
                tmp_keep_reg_132_pp0_iter18_reg <= tmp_keep_reg_132_pp0_iter17_reg;
                tmp_keep_reg_132_pp0_iter19_reg <= tmp_keep_reg_132_pp0_iter18_reg;
                tmp_keep_reg_132_pp0_iter20_reg <= tmp_keep_reg_132_pp0_iter19_reg;
                tmp_keep_reg_132_pp0_iter21_reg <= tmp_keep_reg_132_pp0_iter20_reg;
                tmp_keep_reg_132_pp0_iter22_reg <= tmp_keep_reg_132_pp0_iter21_reg;
                tmp_keep_reg_132_pp0_iter23_reg <= tmp_keep_reg_132_pp0_iter22_reg;
                tmp_keep_reg_132_pp0_iter24_reg <= tmp_keep_reg_132_pp0_iter23_reg;
                tmp_keep_reg_132_pp0_iter25_reg <= tmp_keep_reg_132_pp0_iter24_reg;
                tmp_keep_reg_132_pp0_iter26_reg <= tmp_keep_reg_132_pp0_iter25_reg;
                tmp_keep_reg_132_pp0_iter27_reg <= tmp_keep_reg_132_pp0_iter26_reg;
                tmp_keep_reg_132_pp0_iter28_reg <= tmp_keep_reg_132_pp0_iter27_reg;
                tmp_keep_reg_132_pp0_iter29_reg <= tmp_keep_reg_132_pp0_iter28_reg;
                tmp_keep_reg_132_pp0_iter2_reg <= tmp_keep_reg_132_pp0_iter1_reg;
                tmp_keep_reg_132_pp0_iter30_reg <= tmp_keep_reg_132_pp0_iter29_reg;
                tmp_keep_reg_132_pp0_iter31_reg <= tmp_keep_reg_132_pp0_iter30_reg;
                tmp_keep_reg_132_pp0_iter32_reg <= tmp_keep_reg_132_pp0_iter31_reg;
                tmp_keep_reg_132_pp0_iter33_reg <= tmp_keep_reg_132_pp0_iter32_reg;
                tmp_keep_reg_132_pp0_iter34_reg <= tmp_keep_reg_132_pp0_iter33_reg;
                tmp_keep_reg_132_pp0_iter3_reg <= tmp_keep_reg_132_pp0_iter2_reg;
                tmp_keep_reg_132_pp0_iter4_reg <= tmp_keep_reg_132_pp0_iter3_reg;
                tmp_keep_reg_132_pp0_iter5_reg <= tmp_keep_reg_132_pp0_iter4_reg;
                tmp_keep_reg_132_pp0_iter6_reg <= tmp_keep_reg_132_pp0_iter5_reg;
                tmp_keep_reg_132_pp0_iter7_reg <= tmp_keep_reg_132_pp0_iter6_reg;
                tmp_keep_reg_132_pp0_iter8_reg <= tmp_keep_reg_132_pp0_iter7_reg;
                tmp_keep_reg_132_pp0_iter9_reg <= tmp_keep_reg_132_pp0_iter8_reg;
                tmp_last_reg_142_pp0_iter10_reg <= tmp_last_reg_142_pp0_iter9_reg;
                tmp_last_reg_142_pp0_iter11_reg <= tmp_last_reg_142_pp0_iter10_reg;
                tmp_last_reg_142_pp0_iter12_reg <= tmp_last_reg_142_pp0_iter11_reg;
                tmp_last_reg_142_pp0_iter13_reg <= tmp_last_reg_142_pp0_iter12_reg;
                tmp_last_reg_142_pp0_iter14_reg <= tmp_last_reg_142_pp0_iter13_reg;
                tmp_last_reg_142_pp0_iter15_reg <= tmp_last_reg_142_pp0_iter14_reg;
                tmp_last_reg_142_pp0_iter16_reg <= tmp_last_reg_142_pp0_iter15_reg;
                tmp_last_reg_142_pp0_iter17_reg <= tmp_last_reg_142_pp0_iter16_reg;
                tmp_last_reg_142_pp0_iter18_reg <= tmp_last_reg_142_pp0_iter17_reg;
                tmp_last_reg_142_pp0_iter19_reg <= tmp_last_reg_142_pp0_iter18_reg;
                tmp_last_reg_142_pp0_iter20_reg <= tmp_last_reg_142_pp0_iter19_reg;
                tmp_last_reg_142_pp0_iter21_reg <= tmp_last_reg_142_pp0_iter20_reg;
                tmp_last_reg_142_pp0_iter22_reg <= tmp_last_reg_142_pp0_iter21_reg;
                tmp_last_reg_142_pp0_iter23_reg <= tmp_last_reg_142_pp0_iter22_reg;
                tmp_last_reg_142_pp0_iter24_reg <= tmp_last_reg_142_pp0_iter23_reg;
                tmp_last_reg_142_pp0_iter25_reg <= tmp_last_reg_142_pp0_iter24_reg;
                tmp_last_reg_142_pp0_iter26_reg <= tmp_last_reg_142_pp0_iter25_reg;
                tmp_last_reg_142_pp0_iter27_reg <= tmp_last_reg_142_pp0_iter26_reg;
                tmp_last_reg_142_pp0_iter28_reg <= tmp_last_reg_142_pp0_iter27_reg;
                tmp_last_reg_142_pp0_iter29_reg <= tmp_last_reg_142_pp0_iter28_reg;
                tmp_last_reg_142_pp0_iter2_reg <= tmp_last_reg_142_pp0_iter1_reg;
                tmp_last_reg_142_pp0_iter30_reg <= tmp_last_reg_142_pp0_iter29_reg;
                tmp_last_reg_142_pp0_iter31_reg <= tmp_last_reg_142_pp0_iter30_reg;
                tmp_last_reg_142_pp0_iter32_reg <= tmp_last_reg_142_pp0_iter31_reg;
                tmp_last_reg_142_pp0_iter33_reg <= tmp_last_reg_142_pp0_iter32_reg;
                tmp_last_reg_142_pp0_iter34_reg <= tmp_last_reg_142_pp0_iter33_reg;
                tmp_last_reg_142_pp0_iter3_reg <= tmp_last_reg_142_pp0_iter2_reg;
                tmp_last_reg_142_pp0_iter4_reg <= tmp_last_reg_142_pp0_iter3_reg;
                tmp_last_reg_142_pp0_iter5_reg <= tmp_last_reg_142_pp0_iter4_reg;
                tmp_last_reg_142_pp0_iter6_reg <= tmp_last_reg_142_pp0_iter5_reg;
                tmp_last_reg_142_pp0_iter7_reg <= tmp_last_reg_142_pp0_iter6_reg;
                tmp_last_reg_142_pp0_iter8_reg <= tmp_last_reg_142_pp0_iter7_reg;
                tmp_last_reg_142_pp0_iter9_reg <= tmp_last_reg_142_pp0_iter8_reg;
                tmp_strb_reg_137_pp0_iter10_reg <= tmp_strb_reg_137_pp0_iter9_reg;
                tmp_strb_reg_137_pp0_iter11_reg <= tmp_strb_reg_137_pp0_iter10_reg;
                tmp_strb_reg_137_pp0_iter12_reg <= tmp_strb_reg_137_pp0_iter11_reg;
                tmp_strb_reg_137_pp0_iter13_reg <= tmp_strb_reg_137_pp0_iter12_reg;
                tmp_strb_reg_137_pp0_iter14_reg <= tmp_strb_reg_137_pp0_iter13_reg;
                tmp_strb_reg_137_pp0_iter15_reg <= tmp_strb_reg_137_pp0_iter14_reg;
                tmp_strb_reg_137_pp0_iter16_reg <= tmp_strb_reg_137_pp0_iter15_reg;
                tmp_strb_reg_137_pp0_iter17_reg <= tmp_strb_reg_137_pp0_iter16_reg;
                tmp_strb_reg_137_pp0_iter18_reg <= tmp_strb_reg_137_pp0_iter17_reg;
                tmp_strb_reg_137_pp0_iter19_reg <= tmp_strb_reg_137_pp0_iter18_reg;
                tmp_strb_reg_137_pp0_iter20_reg <= tmp_strb_reg_137_pp0_iter19_reg;
                tmp_strb_reg_137_pp0_iter21_reg <= tmp_strb_reg_137_pp0_iter20_reg;
                tmp_strb_reg_137_pp0_iter22_reg <= tmp_strb_reg_137_pp0_iter21_reg;
                tmp_strb_reg_137_pp0_iter23_reg <= tmp_strb_reg_137_pp0_iter22_reg;
                tmp_strb_reg_137_pp0_iter24_reg <= tmp_strb_reg_137_pp0_iter23_reg;
                tmp_strb_reg_137_pp0_iter25_reg <= tmp_strb_reg_137_pp0_iter24_reg;
                tmp_strb_reg_137_pp0_iter26_reg <= tmp_strb_reg_137_pp0_iter25_reg;
                tmp_strb_reg_137_pp0_iter27_reg <= tmp_strb_reg_137_pp0_iter26_reg;
                tmp_strb_reg_137_pp0_iter28_reg <= tmp_strb_reg_137_pp0_iter27_reg;
                tmp_strb_reg_137_pp0_iter29_reg <= tmp_strb_reg_137_pp0_iter28_reg;
                tmp_strb_reg_137_pp0_iter2_reg <= tmp_strb_reg_137_pp0_iter1_reg;
                tmp_strb_reg_137_pp0_iter30_reg <= tmp_strb_reg_137_pp0_iter29_reg;
                tmp_strb_reg_137_pp0_iter31_reg <= tmp_strb_reg_137_pp0_iter30_reg;
                tmp_strb_reg_137_pp0_iter32_reg <= tmp_strb_reg_137_pp0_iter31_reg;
                tmp_strb_reg_137_pp0_iter33_reg <= tmp_strb_reg_137_pp0_iter32_reg;
                tmp_strb_reg_137_pp0_iter34_reg <= tmp_strb_reg_137_pp0_iter33_reg;
                tmp_strb_reg_137_pp0_iter3_reg <= tmp_strb_reg_137_pp0_iter2_reg;
                tmp_strb_reg_137_pp0_iter4_reg <= tmp_strb_reg_137_pp0_iter3_reg;
                tmp_strb_reg_137_pp0_iter5_reg <= tmp_strb_reg_137_pp0_iter4_reg;
                tmp_strb_reg_137_pp0_iter6_reg <= tmp_strb_reg_137_pp0_iter5_reg;
                tmp_strb_reg_137_pp0_iter7_reg <= tmp_strb_reg_137_pp0_iter6_reg;
                tmp_strb_reg_137_pp0_iter8_reg <= tmp_strb_reg_137_pp0_iter7_reg;
                tmp_strb_reg_137_pp0_iter9_reg <= tmp_strb_reg_137_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                tmp_keep_reg_132 <= a_TKEEP_int_regslice;
                tmp_keep_reg_132_pp0_iter1_reg <= tmp_keep_reg_132;
                tmp_last_reg_142 <= a_TLAST_int_regslice;
                tmp_last_reg_142_pp0_iter1_reg <= tmp_last_reg_142;
                tmp_strb_reg_137 <= a_TSTRB_int_regslice;
                tmp_strb_reg_137_pp0_iter1_reg <= tmp_strb_reg_137;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    a_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_start_int, a_TVALID_int_regslice)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            a_TDATA_blk_n <= a_TVALID_int_regslice;
        else 
            a_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    a_TREADY <= regslice_both_a_V_data_V_U_ack_in;

    a_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            a_TREADY_int_regslice <= ap_const_logic_1;
        else 
            a_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter35, ap_enable_reg_pp0_iter36, ap_block_state1_pp0_stage0_iter0, ap_block_state36_pp0_stage0_iter35, regslice_both_result_V_data_V_U_apdone_blk, ap_block_state37_pp0_stage0_iter36, ap_loop_exit_ready_pp0_iter36_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_loop_exit_ready_pp0_iter36_reg = ap_const_logic_1) and (regslice_both_result_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state37_pp0_stage0_iter36) and (ap_enable_reg_pp0_iter36 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state36_pp0_stage0_iter35) and (ap_enable_reg_pp0_iter35 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter35, ap_enable_reg_pp0_iter36, ap_block_state1_pp0_stage0_iter0, ap_block_state36_pp0_stage0_iter35, regslice_both_result_V_data_V_U_apdone_blk, ap_block_state37_pp0_stage0_iter36, ap_loop_exit_ready_pp0_iter36_reg, ap_start_int, result_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_loop_exit_ready_pp0_iter36_reg = ap_const_logic_1) and (regslice_both_result_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter36 = ap_const_logic_1) and ((result_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state37_pp0_stage0_iter36))) or ((ap_enable_reg_pp0_iter35 = ap_const_logic_1) and ((result_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state36_pp0_stage0_iter35))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter35, ap_enable_reg_pp0_iter36, ap_block_state1_pp0_stage0_iter0, ap_block_state36_pp0_stage0_iter35, regslice_both_result_V_data_V_U_apdone_blk, ap_block_state37_pp0_stage0_iter36, ap_loop_exit_ready_pp0_iter36_reg, ap_start_int, result_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_loop_exit_ready_pp0_iter36_reg = ap_const_logic_1) and (regslice_both_result_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter36 = ap_const_logic_1) and ((result_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state37_pp0_stage0_iter36))) or ((ap_enable_reg_pp0_iter35 = ap_const_logic_1) and ((result_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state36_pp0_stage0_iter35))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(a_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_const_logic_0 = a_TVALID_int_regslice);
    end process;


    ap_block_state36_pp0_stage0_iter35_assign_proc : process(result_TREADY_int_regslice)
    begin
                ap_block_state36_pp0_stage0_iter35 <= (result_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state37_pp0_stage0_iter36_assign_proc : process(regslice_both_result_V_data_V_U_apdone_blk, result_TREADY_int_regslice)
    begin
                ap_block_state37_pp0_stage0_iter36 <= ((result_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_result_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, tmp_last_fu_102_p1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_last_fu_102_p1 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_loop_exit_ready_pp0_iter36_reg, ap_block_pp0_stage0_subdone, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter36_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31, ap_enable_reg_pp0_iter32, ap_enable_reg_pp0_iter33, ap_enable_reg_pp0_iter34, ap_enable_reg_pp0_iter35, ap_enable_reg_pp0_iter36)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = 
    ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter36 = ap_const_logic_0) and (ap_enable_reg_pp0_iter35 = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_0) and (ap_enable_reg_pp0_iter33 = ap_const_logic_0) and (ap_enable_reg_pp0_iter32 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    grp_fu_106_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_106_ce <= ap_const_logic_1;
        else 
            grp_fu_106_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_106_p1 <= ap_const_lv32_D(5 - 1 downto 0);
    res_fu_116_p2 <= "1" when (trunc_ln16_fu_112_p1 = ap_const_lv5_0) else "0";

    result_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter35, ap_enable_reg_pp0_iter36, ap_block_pp0_stage0, result_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter36 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter35 = ap_const_logic_1)))) then 
            result_TDATA_blk_n <= result_TREADY_int_regslice;
        else 
            result_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    result_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_fu_116_p2),32));
    result_TVALID <= regslice_both_result_V_data_V_U_vld_out;

    result_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter35, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter35 = ap_const_logic_1))) then 
            result_TVALID_int_regslice <= ap_const_logic_1;
        else 
            result_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_last_fu_102_p1 <= a_TLAST_int_regslice;
    trunc_ln16_fu_112_p1 <= grp_fu_106_p2(5 - 1 downto 0);
end behav;
