// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dct_dct_1d (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;

reg  signed [15:0] p_read_1_reg_751;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] p_read_2_reg_758;
reg  signed [15:0] p_read_2_reg_758_pp0_iter1_reg;
reg  signed [15:0] p_read_2_reg_758_pp0_iter2_reg;
reg  signed [15:0] p_read_3_reg_766;
reg  signed [15:0] p_read_4_reg_773;
reg  signed [15:0] p_read_5_reg_778;
reg  signed [15:0] p_read_5_reg_778_pp0_iter1_reg;
reg  signed [15:0] p_read_6_reg_784;
reg  signed [15:0] p_read_7_reg_791;
reg  signed [15:0] p_read21_reg_798;
wire  signed [16:0] sext_ln21_fu_98_p1;
reg  signed [16:0] sext_ln21_reg_804;
wire  signed [28:0] tmp19_cast_fu_140_p1;
wire  signed [28:0] sext_ln21_15_fu_144_p1;
reg  signed [28:0] sext_ln21_15_reg_815;
reg  signed [28:0] sext_ln21_15_reg_815_pp0_iter1_reg;
reg  signed [28:0] sext_ln21_15_reg_815_pp0_iter2_reg;
wire  signed [28:0] sext_ln21_17_fu_148_p1;
wire  signed [28:0] sext_ln21_1_fu_152_p1;
wire  signed [28:0] sext_ln21_11_fu_176_p1;
reg  signed [28:0] sext_ln21_11_reg_833;
reg   [15:0] trunc_ln_reg_839;
reg   [15:0] trunc_ln_reg_839_pp0_iter2_reg;
reg   [15:0] trunc_ln_reg_839_pp0_iter3_reg;
wire  signed [28:0] sext_ln21_12_fu_255_p1;
reg  signed [28:0] sext_ln21_12_reg_844;
wire  signed [28:0] tmp7_cast70_fu_264_p1;
wire  signed [28:0] sext_ln21_14_fu_284_p1;
reg  signed [28:0] sext_ln21_14_reg_856;
wire  signed [28:0] tmp25_cast72_fu_293_p1;
reg   [15:0] trunc_ln23_4_reg_868;
reg   [15:0] trunc_ln23_4_reg_868_pp0_iter2_reg;
reg   [15:0] trunc_ln23_4_reg_868_pp0_iter3_reg;
wire  signed [28:0] sext_ln23_fu_360_p1;
wire  signed [28:0] mul_ln21_fu_380_p2;
wire  signed [28:0] mul_ln21_3_fu_385_p2;
wire  signed [28:0] mul_ln21_5_fu_390_p2;
wire  signed [28:0] mul_ln21_7_fu_398_p2;
wire  signed [28:0] mul_ln21_11_fu_404_p2;
wire  signed [28:0] mul_ln21_1_fu_413_p2;
wire   [28:0] grp_fu_570_p4;
wire   [28:0] grp_fu_580_p3;
wire   [28:0] grp_fu_588_p3;
wire  signed [28:0] grp_fu_596_p4;
reg  signed [28:0] add_ln23_16_reg_924;
wire  signed [28:0] mul_ln21_9_fu_419_p2;
wire   [28:0] grp_fu_606_p3;
wire   [28:0] grp_fu_614_p3;
wire  signed [28:0] mul_ln21_13_fu_425_p2;
wire   [28:0] grp_fu_622_p3;
wire  signed [15:0] sext_ln21_fu_98_p0;
wire    ap_block_pp0_stage0;
wire  signed [15:0] sext_ln21_4_fu_102_p0;
wire  signed [15:0] sext_ln11_fu_106_p0;
wire  signed [15:0] sext_ln11_1_fu_110_p0;
wire  signed [15:0] sext_ln21_10_fu_114_p0;
wire  signed [16:0] sext_ln21_4_fu_102_p1;
wire   [16:0] tmp17_fu_118_p2;
wire  signed [17:0] tmp17_cast_fu_124_p1;
wire  signed [17:0] sext_ln11_fu_106_p1;
wire   [17:0] tmp18_fu_128_p2;
wire  signed [17:0] sext_ln21_10_fu_114_p1;
wire   [17:0] tmp19_fu_134_p2;
wire  signed [15:0] sext_ln21_15_fu_144_p0;
wire  signed [15:0] sext_ln21_17_fu_148_p0;
wire   [15:0] tmp1_fu_190_p2;
wire   [15:0] tmp_fu_186_p2;
wire   [15:0] tmp218_fu_194_p2;
wire   [15:0] tmp5716_fu_215_p2;
wire   [28:0] tmp_1_fu_208_p3;
wire   [28:0] shl_ln_fu_179_p3;
wire   [28:0] add_ln21_fu_227_p2;
wire   [28:0] tmp6_fu_219_p3;
wire   [28:0] tmp_3_fu_233_p2;
wire   [28:0] tmp3_fu_200_p3;
wire   [28:0] add_ln23_fu_239_p2;
wire  signed [16:0] sext_ln21_3_fu_158_p1;
wire  signed [16:0] sext_ln21_6_fu_164_p1;
wire   [16:0] tmp7_fu_258_p2;
wire  signed [16:0] sext_ln21_2_fu_155_p1;
wire   [16:0] tmp11_fu_268_p2;
wire  signed [17:0] tmp11_cast_fu_274_p1;
wire  signed [17:0] sext_ln21_5_fu_161_p1;
wire  signed [16:0] sext_ln21_7_fu_167_p1;
wire   [16:0] tmp25_fu_287_p2;
wire  signed [16:0] tmp27_fu_297_p2;
wire   [15:0] empty_fu_307_p1;
wire  signed [28:0] tmp27_cast_fu_303_p1;
wire   [28:0] p_shl1_fu_311_p3;
wire   [28:0] p_shl_fu_325_p3;
wire   [28:0] sub_ln23_fu_333_p2;
wire   [28:0] tmp28_fu_319_p2;
wire   [28:0] add_ln23_4_fu_339_p2;
wire  signed [16:0] sext_ln21_9_fu_173_p1;
wire   [16:0] tmp35_fu_355_p2;
wire   [16:0] tmp39_fu_364_p2;
wire  signed [17:0] tmp39_cast_fu_370_p1;
wire  signed [15:0] mul_ln21_fu_380_p0;
wire   [14:0] mul_ln21_fu_380_p1;
wire  signed [15:0] mul_ln21_3_fu_385_p0;
wire  signed [14:0] mul_ln21_3_fu_385_p1;
wire  signed [15:0] mul_ln21_5_fu_390_p0;
wire  signed [14:0] mul_ln21_5_fu_390_p1;
wire  signed [15:0] mul_ln21_7_fu_398_p0;
wire  signed [28:0] sext_ln21_16_fu_395_p1;
wire   [14:0] mul_ln21_7_fu_398_p1;
wire  signed [15:0] mul_ln21_11_fu_404_p0;
wire  signed [14:0] mul_ln21_11_fu_404_p1;
wire  signed [15:0] mul_ln21_1_fu_413_p0;
wire  signed [28:0] sext_ln21_13_fu_410_p1;
wire  signed [14:0] mul_ln21_1_fu_413_p1;
wire  signed [15:0] mul_ln21_9_fu_419_p0;
wire   [14:0] mul_ln21_9_fu_419_p1;
wire  signed [15:0] mul_ln21_13_fu_425_p0;
wire  signed [14:0] mul_ln21_13_fu_425_p1;
wire  signed [28:0] add_ln23_12_fu_430_p0;
wire   [28:0] grp_fu_639_p3;
wire  signed [28:0] grp_fu_648_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln23_12_fu_430_p2;
wire  signed [28:0] add_ln23_1_fu_434_p1;
wire   [28:0] grp_fu_630_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln23_1_fu_434_p2;
wire  signed [28:0] trunc_ln23_2_fu_449_p1;
wire   [28:0] grp_fu_657_p4;
wire  signed [28:0] add_ln23_18_fu_458_p0;
wire   [28:0] grp_fu_677_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln23_18_fu_458_p2;
wire  signed [28:0] add_ln23_3_fu_462_p1;
wire   [28:0] grp_fu_668_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln23_3_fu_462_p2;
wire  signed [28:0] add_ln23_23_fu_477_p0;
wire   [28:0] grp_fu_704_p3;
wire  signed [28:0] grp_fu_695_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln23_23_fu_477_p2;
wire  signed [28:0] add_ln23_5_fu_481_p1;
wire   [28:0] grp_fu_686_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln23_5_fu_481_p2;
wire  signed [28:0] trunc_ln23_6_fu_496_p1;
wire   [28:0] grp_fu_713_p4;
wire  signed [28:0] add_ln23_29_fu_505_p0;
wire   [28:0] grp_fu_742_p3;
wire  signed [28:0] grp_fu_733_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln23_29_fu_505_p2;
wire  signed [28:0] add_ln23_7_fu_509_p1;
wire   [28:0] grp_fu_724_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln23_7_fu_509_p2;
wire  signed [15:0] grp_fu_570_p0;
wire  signed [15:0] grp_fu_570_p1;
wire  signed [16:0] sext_ln11_1_fu_110_p1;
wire   [11:0] grp_fu_570_p2;
wire  signed [17:0] grp_fu_580_p0;
wire   [13:0] grp_fu_580_p1;
wire   [12:0] grp_fu_580_p2;
wire   [13:0] grp_fu_588_p1;
wire  signed [15:0] grp_fu_596_p0;
wire  signed [15:0] grp_fu_596_p1;
wire   [12:0] grp_fu_596_p2;
wire  signed [15:0] grp_fu_606_p0;
wire  signed [14:0] grp_fu_606_p1;
wire  signed [17:0] grp_fu_614_p0;
wire   [12:0] grp_fu_614_p1;
wire   [12:0] grp_fu_614_p2;
wire  signed [15:0] grp_fu_622_p0;
wire   [13:0] grp_fu_622_p1;
wire  signed [15:0] grp_fu_630_p0;
wire   [13:0] grp_fu_630_p1;
wire  signed [14:0] grp_fu_639_p1;
wire   [12:0] grp_fu_639_p2;
wire  signed [16:0] grp_fu_648_p0;
wire   [12:0] grp_fu_648_p1;
wire  signed [17:0] grp_fu_657_p0;
wire  signed [15:0] grp_fu_657_p1;
wire  signed [17:0] sext_ln21_8_fu_170_p1;
wire   [12:0] grp_fu_657_p2;
wire  signed [15:0] grp_fu_668_p0;
wire   [13:0] grp_fu_668_p1;
wire  signed [16:0] grp_fu_677_p0;
wire   [11:0] grp_fu_677_p1;
wire   [12:0] grp_fu_677_p2;
wire  signed [14:0] grp_fu_686_p1;
wire  signed [16:0] grp_fu_695_p0;
wire   [11:0] grp_fu_695_p1;
wire  signed [16:0] grp_fu_704_p0;
wire   [12:0] grp_fu_704_p1;
wire   [12:0] grp_fu_704_p2;
wire  signed [17:0] grp_fu_713_p0;
wire  signed [15:0] grp_fu_713_p1;
wire   [13:0] grp_fu_713_p2;
wire   [13:0] grp_fu_724_p1;
wire  signed [16:0] grp_fu_733_p0;
wire   [12:0] grp_fu_733_p1;
wire  signed [16:0] grp_fu_742_p0;
wire   [11:0] grp_fu_742_p1;
wire   [12:0] grp_fu_742_p2;
reg    grp_fu_570_ce;
reg    grp_fu_580_ce;
reg    grp_fu_588_ce;
reg    grp_fu_596_ce;
reg    grp_fu_606_ce;
reg    grp_fu_614_ce;
reg    grp_fu_622_ce;
reg    grp_fu_630_ce;
reg    grp_fu_639_ce;
reg    grp_fu_648_ce;
reg    grp_fu_657_ce;
reg    grp_fu_668_ce;
reg    grp_fu_677_ce;
reg    grp_fu_686_ce;
reg    grp_fu_695_ce;
reg    grp_fu_704_ce;
reg    grp_fu_713_ce;
reg    grp_fu_724_ce;
reg    grp_fu_733_ce;
reg    grp_fu_742_ce;
reg    ap_ce_reg;
reg   [15:0] p_read_int_reg;
reg   [15:0] p_read1_int_reg;
reg   [15:0] p_read2_int_reg;
reg   [15:0] p_read3_int_reg;
reg   [15:0] p_read4_int_reg;
reg  signed [15:0] p_read5_int_reg;
reg   [15:0] p_read6_int_reg;
reg   [15:0] p_read7_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
reg   [15:0] ap_return_7_int_reg;

dct_mul_16s_15ns_29_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_0_U11(
    .din0(mul_ln21_fu_380_p0),
    .din1(mul_ln21_fu_380_p1),
    .dout(mul_ln21_fu_380_p2)
);

dct_mul_16s_15s_29_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_0_U12(
    .din0(mul_ln21_3_fu_385_p0),
    .din1(mul_ln21_3_fu_385_p1),
    .dout(mul_ln21_3_fu_385_p2)
);

dct_mul_16s_15s_29_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_0_U13(
    .din0(mul_ln21_5_fu_390_p0),
    .din1(mul_ln21_5_fu_390_p1),
    .dout(mul_ln21_5_fu_390_p2)
);

dct_mul_16s_15ns_29_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_0_U14(
    .din0(mul_ln21_7_fu_398_p0),
    .din1(mul_ln21_7_fu_398_p1),
    .dout(mul_ln21_7_fu_398_p2)
);

dct_mul_16s_15s_29_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_0_U15(
    .din0(mul_ln21_11_fu_404_p0),
    .din1(mul_ln21_11_fu_404_p1),
    .dout(mul_ln21_11_fu_404_p2)
);

dct_mul_16s_15s_29_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_0_U16(
    .din0(mul_ln21_1_fu_413_p0),
    .din1(mul_ln21_1_fu_413_p1),
    .dout(mul_ln21_1_fu_413_p2)
);

dct_mul_16s_15ns_29_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_0_U17(
    .din0(mul_ln21_9_fu_419_p0),
    .din1(mul_ln21_9_fu_419_p1),
    .dout(mul_ln21_9_fu_419_p2)
);

dct_mul_16s_15s_29_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_0_U18(
    .din0(mul_ln21_13_fu_425_p0),
    .din1(mul_ln21_13_fu_425_p1),
    .dout(mul_ln21_13_fu_425_p2)
);

dct_ama_submuladd_16s_16s_12ns_29s_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_16s_16s_12ns_29s_29_4_0_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_570_p0),
    .din1(grp_fu_570_p1),
    .din2(grp_fu_570_p2),
    .din3(mul_ln21_fu_380_p2),
    .ce(grp_fu_570_ce),
    .dout(grp_fu_570_p4)
);

dct_mac_muladd_18s_14ns_13ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_18s_14ns_13ns_29_4_0_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_580_p0),
    .din1(grp_fu_580_p1),
    .din2(grp_fu_580_p2),
    .ce(grp_fu_580_ce),
    .dout(grp_fu_580_p3)
);

dct_mac_muladd_16s_14ns_29s_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29s_29_4_0_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_read5_int_reg),
    .din1(grp_fu_588_p1),
    .din2(mul_ln21_3_fu_385_p2),
    .ce(grp_fu_588_ce),
    .dout(grp_fu_588_p3)
);

dct_ama_submuladd_16s_16s_13ns_29s_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_16s_16s_13ns_29s_29_4_0_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_596_p0),
    .din1(grp_fu_596_p1),
    .din2(grp_fu_596_p2),
    .din3(mul_ln21_5_fu_390_p2),
    .ce(grp_fu_596_ce),
    .dout(grp_fu_596_p4)
);

dct_mac_muladd_16s_15s_29s_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_0_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_606_p0),
    .din1(grp_fu_606_p1),
    .din2(mul_ln21_7_fu_398_p2),
    .ce(grp_fu_606_ce),
    .dout(grp_fu_606_p3)
);

dct_mac_muladd_18s_13ns_13ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_18s_13ns_13ns_29_4_0_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_614_p0),
    .din1(grp_fu_614_p1),
    .din2(grp_fu_614_p2),
    .ce(grp_fu_614_ce),
    .dout(grp_fu_614_p3)
);

dct_mac_muladd_16s_14ns_29s_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29s_29_4_0_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_622_p0),
    .din1(grp_fu_622_p1),
    .din2(mul_ln21_11_fu_404_p2),
    .ce(grp_fu_622_ce),
    .dout(grp_fu_622_p3)
);

dct_mac_muladd_16s_14ns_29ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_0_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_630_p0),
    .din1(grp_fu_630_p1),
    .din2(grp_fu_570_p4),
    .ce(grp_fu_630_ce),
    .dout(grp_fu_630_p3)
);

dct_mac_muladd_16s_15s_13ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_13ns_29_4_0_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_read_1_reg_751),
    .din1(grp_fu_639_p1),
    .din2(grp_fu_639_p2),
    .ce(grp_fu_639_ce),
    .dout(grp_fu_639_p3)
);

dct_mac_muladd_17s_13ns_29s_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_29s_29_4_0_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_648_p0),
    .din1(grp_fu_648_p1),
    .din2(mul_ln21_1_fu_413_p2),
    .ce(grp_fu_648_ce),
    .dout(grp_fu_648_p3)
);

dct_ama_addmuladd_18s_16s_13ns_29ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_addmuladd_18s_16s_13ns_29ns_29_4_0_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_657_p0),
    .din1(grp_fu_657_p1),
    .din2(grp_fu_657_p2),
    .din3(grp_fu_580_p3),
    .ce(grp_fu_657_ce),
    .dout(grp_fu_657_p4)
);

dct_mac_muladd_16s_14ns_29ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_0_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_668_p0),
    .din1(grp_fu_668_p1),
    .din2(grp_fu_588_p3),
    .ce(grp_fu_668_ce),
    .dout(grp_fu_668_p3)
);

dct_mac_muladd_17s_12ns_13ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_13ns_29_4_0_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_677_p0),
    .din1(grp_fu_677_p1),
    .din2(grp_fu_677_p2),
    .ce(grp_fu_677_ce),
    .dout(grp_fu_677_p3)
);

dct_mac_muladd_16s_15s_29ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29ns_29_4_0_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_read_7_reg_791),
    .din1(grp_fu_686_p1),
    .din2(grp_fu_606_p3),
    .ce(grp_fu_686_ce),
    .dout(grp_fu_686_p3)
);

dct_mac_muladd_17s_12ns_29s_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_29s_29_4_0_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_695_p0),
    .din1(grp_fu_695_p1),
    .din2(mul_ln21_9_fu_419_p2),
    .ce(grp_fu_695_ce),
    .dout(grp_fu_695_p3)
);

dct_mac_muladd_17s_13ns_13ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_13ns_29_4_0_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_704_p0),
    .din1(grp_fu_704_p1),
    .din2(grp_fu_704_p2),
    .ce(grp_fu_704_ce),
    .dout(grp_fu_704_p3)
);

dct_ama_submuladd_18s_16s_14ns_29ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_18s_16s_14ns_29ns_29_4_0_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_713_p0),
    .din1(grp_fu_713_p1),
    .din2(grp_fu_713_p2),
    .din3(grp_fu_614_p3),
    .ce(grp_fu_713_ce),
    .dout(grp_fu_713_p4)
);

dct_mac_muladd_16s_14ns_29ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_0_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_read_6_reg_784),
    .din1(grp_fu_724_p1),
    .din2(grp_fu_622_p3),
    .ce(grp_fu_724_ce),
    .dout(grp_fu_724_p3)
);

dct_mac_muladd_17s_13ns_29s_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_29s_29_4_0_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_733_p0),
    .din1(grp_fu_733_p1),
    .din2(mul_ln21_13_fu_425_p2),
    .ce(grp_fu_733_ce),
    .dout(grp_fu_733_p3)
);

dct_mac_muladd_17s_12ns_13ns_29_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_13ns_29_4_0_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_742_p0),
    .din1(grp_fu_742_p1),
    .din2(grp_fu_742_p2),
    .ce(grp_fu_742_ce),
    .dout(grp_fu_742_p3)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln23_16_reg_924 <= grp_fu_596_p4;
        p_read21_reg_798 <= p_read_int_reg;
        p_read_1_reg_751 <= p_read7_int_reg;
        p_read_2_reg_758 <= p_read6_int_reg;
        p_read_2_reg_758_pp0_iter1_reg <= p_read_2_reg_758;
        p_read_2_reg_758_pp0_iter2_reg <= p_read_2_reg_758_pp0_iter1_reg;
        p_read_3_reg_766 <= p_read5_int_reg;
        p_read_4_reg_773 <= p_read4_int_reg;
        p_read_5_reg_778 <= p_read3_int_reg;
        p_read_5_reg_778_pp0_iter1_reg <= p_read_5_reg_778;
        p_read_6_reg_784 <= p_read2_int_reg;
        p_read_7_reg_791 <= p_read1_int_reg;
        sext_ln21_11_reg_833 <= sext_ln21_11_fu_176_p1;
        sext_ln21_12_reg_844 <= sext_ln21_12_fu_255_p1;
        sext_ln21_14_reg_856 <= sext_ln21_14_fu_284_p1;
        sext_ln21_15_reg_815 <= sext_ln21_15_fu_144_p1;
        sext_ln21_15_reg_815_pp0_iter1_reg <= sext_ln21_15_reg_815;
        sext_ln21_15_reg_815_pp0_iter2_reg <= sext_ln21_15_reg_815_pp0_iter1_reg;
        sext_ln21_reg_804 <= sext_ln21_fu_98_p1;
        trunc_ln23_4_reg_868 <= {{add_ln23_4_fu_339_p2[28:13]}};
        trunc_ln23_4_reg_868_pp0_iter2_reg <= trunc_ln23_4_reg_868;
        trunc_ln23_4_reg_868_pp0_iter3_reg <= trunc_ln23_4_reg_868_pp0_iter2_reg;
        trunc_ln_reg_839 <= {{add_ln23_fu_239_p2[28:13]}};
        trunc_ln_reg_839_pp0_iter2_reg <= trunc_ln_reg_839;
        trunc_ln_reg_839_pp0_iter3_reg <= trunc_ln_reg_839_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= trunc_ln_reg_839_pp0_iter3_reg;
        ap_return_1_int_reg <= {{add_ln23_1_fu_434_p2[28:13]}};
        ap_return_2_int_reg <= {{trunc_ln23_2_fu_449_p1[28:13]}};
        ap_return_3_int_reg <= {{add_ln23_3_fu_462_p2[28:13]}};
        ap_return_4_int_reg <= trunc_ln23_4_reg_868_pp0_iter3_reg;
        ap_return_5_int_reg <= {{add_ln23_5_fu_481_p2[28:13]}};
        ap_return_6_int_reg <= {{trunc_ln23_6_fu_496_p1[28:13]}};
        ap_return_7_int_reg <= {{add_ln23_7_fu_509_p2[28:13]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read6_int_reg <= p_read6;
        p_read7_int_reg <= p_read7;
        p_read_int_reg <= p_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = trunc_ln_reg_839_pp0_iter3_reg;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = {{add_ln23_1_fu_434_p2[28:13]}};
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = {{trunc_ln23_2_fu_449_p1[28:13]}};
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = {{add_ln23_3_fu_462_p2[28:13]}};
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = trunc_ln23_4_reg_868_pp0_iter3_reg;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = {{add_ln23_5_fu_481_p2[28:13]}};
    end else begin
        ap_return_5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = {{trunc_ln23_6_fu_496_p1[28:13]}};
    end else begin
        ap_return_6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = {{add_ln23_7_fu_509_p2[28:13]}};
    end else begin
        ap_return_7 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_570_ce = 1'b1;
    end else begin
        grp_fu_570_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_580_ce = 1'b1;
    end else begin
        grp_fu_580_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_588_ce = 1'b1;
    end else begin
        grp_fu_588_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_596_ce = 1'b1;
    end else begin
        grp_fu_596_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_606_ce = 1'b1;
    end else begin
        grp_fu_606_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_614_ce = 1'b1;
    end else begin
        grp_fu_614_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_622_ce = 1'b1;
    end else begin
        grp_fu_622_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_630_ce = 1'b1;
    end else begin
        grp_fu_630_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_639_ce = 1'b1;
    end else begin
        grp_fu_639_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_648_ce = 1'b1;
    end else begin
        grp_fu_648_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_657_ce = 1'b1;
    end else begin
        grp_fu_657_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_668_ce = 1'b1;
    end else begin
        grp_fu_668_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_677_ce = 1'b1;
    end else begin
        grp_fu_677_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_686_ce = 1'b1;
    end else begin
        grp_fu_686_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_695_ce = 1'b1;
    end else begin
        grp_fu_695_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_704_ce = 1'b1;
    end else begin
        grp_fu_704_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_713_ce = 1'b1;
    end else begin
        grp_fu_713_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_724_ce = 1'b1;
    end else begin
        grp_fu_724_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_733_ce = 1'b1;
    end else begin
        grp_fu_733_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_742_ce = 1'b1;
    end else begin
        grp_fu_742_ce = 1'b0;
    end
end

assign add_ln21_fu_227_p2 = (tmp_1_fu_208_p3 + shl_ln_fu_179_p3);

assign add_ln23_12_fu_430_p0 = grp_fu_639_p3;

assign add_ln23_12_fu_430_p2 = ($signed(add_ln23_12_fu_430_p0) + $signed(grp_fu_648_p3));

assign add_ln23_18_fu_458_p0 = grp_fu_677_p3;

assign add_ln23_18_fu_458_p2 = ($signed(add_ln23_18_fu_458_p0) + $signed(add_ln23_16_reg_924));

assign add_ln23_1_fu_434_p1 = grp_fu_630_p3;

assign add_ln23_1_fu_434_p2 = ($signed(add_ln23_12_fu_430_p2) + $signed(add_ln23_1_fu_434_p1));

assign add_ln23_23_fu_477_p0 = grp_fu_704_p3;

assign add_ln23_23_fu_477_p2 = ($signed(add_ln23_23_fu_477_p0) + $signed(grp_fu_695_p3));

assign add_ln23_29_fu_505_p0 = grp_fu_742_p3;

assign add_ln23_29_fu_505_p2 = ($signed(add_ln23_29_fu_505_p0) + $signed(grp_fu_733_p3));

assign add_ln23_3_fu_462_p1 = grp_fu_668_p3;

assign add_ln23_3_fu_462_p2 = ($signed(add_ln23_18_fu_458_p2) + $signed(add_ln23_3_fu_462_p1));

assign add_ln23_4_fu_339_p2 = (sub_ln23_fu_333_p2 + tmp28_fu_319_p2);

assign add_ln23_5_fu_481_p1 = grp_fu_686_p3;

assign add_ln23_5_fu_481_p2 = ($signed(add_ln23_23_fu_477_p2) + $signed(add_ln23_5_fu_481_p1));

assign add_ln23_7_fu_509_p1 = grp_fu_724_p3;

assign add_ln23_7_fu_509_p2 = ($signed(add_ln23_29_fu_505_p2) + $signed(add_ln23_7_fu_509_p1));

assign add_ln23_fu_239_p2 = (tmp_3_fu_233_p2 + tmp3_fu_200_p3);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign empty_fu_307_p1 = tmp27_fu_297_p2[15:0];

assign grp_fu_570_p0 = sext_ln21_4_fu_102_p1;

assign grp_fu_570_p1 = sext_ln11_1_fu_110_p1;

assign grp_fu_570_p2 = 29'd2260;

assign grp_fu_580_p0 = tmp19_cast_fu_140_p1;

assign grp_fu_580_p1 = 29'd10703;

assign grp_fu_580_p2 = 29'd4096;

assign grp_fu_588_p1 = 29'd11363;

assign grp_fu_596_p0 = sext_ln11_1_fu_110_p1;

assign grp_fu_596_p1 = sext_ln21_4_fu_102_p1;

assign grp_fu_596_p2 = 29'd6436;

assign grp_fu_606_p0 = sext_ln21_17_fu_148_p1;

assign grp_fu_606_p1 = 29'd536861280;

assign grp_fu_614_p0 = tmp19_cast_fu_140_p1;

assign grp_fu_614_p1 = 29'd4433;

assign grp_fu_614_p2 = 29'd4096;

assign grp_fu_622_p0 = sext_ln21_17_fu_148_p1;

assign grp_fu_622_p1 = 29'd11363;

assign grp_fu_630_p0 = sext_ln21_1_fu_152_p1;

assign grp_fu_630_p1 = 29'd11363;

assign grp_fu_639_p1 = 29'd536859550;

assign grp_fu_639_p2 = 29'd4096;

assign grp_fu_648_p0 = tmp7_cast70_fu_264_p1;

assign grp_fu_648_p1 = 29'd6436;

assign grp_fu_657_p0 = ($signed(tmp11_cast_fu_274_p1) - $signed(sext_ln21_5_fu_161_p1));

assign grp_fu_657_p1 = sext_ln21_8_fu_170_p1;

assign grp_fu_657_p2 = 29'd4433;

assign grp_fu_668_p0 = sext_ln21_1_fu_152_p1;

assign grp_fu_668_p1 = 29'd9633;

assign grp_fu_677_p0 = tmp25_cast72_fu_293_p1;

assign grp_fu_677_p1 = 29'd2260;

assign grp_fu_677_p2 = 29'd4096;

assign grp_fu_686_p1 = 29'd536859550;

assign grp_fu_695_p0 = tmp7_cast70_fu_264_p1;

assign grp_fu_695_p1 = 29'd2260;

assign grp_fu_704_p0 = sext_ln23_fu_360_p1;

assign grp_fu_704_p1 = 29'd6436;

assign grp_fu_704_p2 = 29'd4096;

assign grp_fu_713_p0 = ($signed(tmp39_cast_fu_370_p1) + $signed(sext_ln21_5_fu_161_p1));

assign grp_fu_713_p1 = sext_ln21_8_fu_170_p1;

assign grp_fu_713_p2 = 29'd10703;

assign grp_fu_724_p1 = 29'd9633;

assign grp_fu_733_p0 = tmp25_cast72_fu_293_p1;

assign grp_fu_733_p1 = 29'd6436;

assign grp_fu_742_p0 = sext_ln23_fu_360_p1;

assign grp_fu_742_p1 = 29'd2260;

assign grp_fu_742_p2 = 29'd4096;

assign mul_ln21_11_fu_404_p0 = sext_ln21_16_fu_395_p1;

assign mul_ln21_11_fu_404_p1 = 29'd536859550;

assign mul_ln21_13_fu_425_p0 = sext_ln21_15_reg_815_pp0_iter2_reg;

assign mul_ln21_13_fu_425_p1 = 29'd536861280;

assign mul_ln21_1_fu_413_p0 = sext_ln21_13_fu_410_p1;

assign mul_ln21_1_fu_413_p1 = 29'd536861280;

assign mul_ln21_3_fu_385_p0 = sext_ln21_14_reg_856;

assign mul_ln21_3_fu_385_p1 = 29'd536859550;

assign mul_ln21_5_fu_390_p0 = sext_ln21_11_reg_833;

assign mul_ln21_5_fu_390_p1 = 29'd536861280;

assign mul_ln21_7_fu_398_p0 = sext_ln21_16_fu_395_p1;

assign mul_ln21_7_fu_398_p1 = 29'd9633;

assign mul_ln21_9_fu_419_p0 = sext_ln21_13_fu_410_p1;

assign mul_ln21_9_fu_419_p1 = 29'd11363;

assign mul_ln21_fu_380_p0 = sext_ln21_12_reg_844;

assign mul_ln21_fu_380_p1 = 29'd9633;

assign p_shl1_fu_311_p3 = {{empty_fu_307_p1}, {13'd0}};

assign p_shl_fu_325_p3 = {{tmp_fu_186_p2}, {13'd0}};

assign sext_ln11_1_fu_110_p0 = p_read4_int_reg;

assign sext_ln11_1_fu_110_p1 = sext_ln11_1_fu_110_p0;

assign sext_ln11_fu_106_p0 = p_read4_int_reg;

assign sext_ln11_fu_106_p1 = sext_ln11_fu_106_p0;

assign sext_ln21_10_fu_114_p0 = p_read7_int_reg;

assign sext_ln21_10_fu_114_p1 = sext_ln21_10_fu_114_p0;

assign sext_ln21_11_fu_176_p1 = p_read_1_reg_751;

assign sext_ln21_12_fu_255_p1 = p_read_7_reg_791;

assign sext_ln21_13_fu_410_p1 = p_read_2_reg_758_pp0_iter2_reg;

assign sext_ln21_14_fu_284_p1 = p_read_6_reg_784;

assign sext_ln21_15_fu_144_p0 = p_read5_int_reg;

assign sext_ln21_15_fu_144_p1 = sext_ln21_15_fu_144_p0;

assign sext_ln21_16_fu_395_p1 = p_read_5_reg_778_pp0_iter1_reg;

assign sext_ln21_17_fu_148_p0 = p_read4_int_reg;

assign sext_ln21_17_fu_148_p1 = sext_ln21_17_fu_148_p0;

assign sext_ln21_1_fu_152_p1 = p_read21_reg_798;

assign sext_ln21_2_fu_155_p1 = p_read_7_reg_791;

assign sext_ln21_3_fu_158_p1 = p_read_6_reg_784;

assign sext_ln21_4_fu_102_p0 = p_read3_int_reg;

assign sext_ln21_4_fu_102_p1 = sext_ln21_4_fu_102_p0;

assign sext_ln21_5_fu_161_p1 = p_read_3_reg_766;

assign sext_ln21_6_fu_164_p1 = p_read_3_reg_766;

assign sext_ln21_7_fu_167_p1 = p_read_2_reg_758;

assign sext_ln21_8_fu_170_p1 = p_read_2_reg_758;

assign sext_ln21_9_fu_173_p1 = p_read_1_reg_751;

assign sext_ln21_fu_98_p0 = p_read_int_reg;

assign sext_ln21_fu_98_p1 = sext_ln21_fu_98_p0;

assign sext_ln23_fu_360_p1 = $signed(tmp35_fu_355_p2);

assign shl_ln_fu_179_p3 = {{p_read_1_reg_751}, {13'd0}};

assign sub_ln23_fu_333_p2 = (tmp_3_fu_233_p2 - p_shl_fu_325_p3);

assign tmp11_cast_fu_274_p1 = $signed(tmp11_fu_268_p2);

assign tmp11_fu_268_p2 = ($signed(sext_ln21_2_fu_155_p1) - $signed(sext_ln21_3_fu_158_p1));

assign tmp17_cast_fu_124_p1 = $signed(tmp17_fu_118_p2);

assign tmp17_fu_118_p2 = ($signed(sext_ln21_fu_98_p1) - $signed(sext_ln21_4_fu_102_p1));

assign tmp18_fu_128_p2 = ($signed(tmp17_cast_fu_124_p1) - $signed(sext_ln11_fu_106_p1));

assign tmp19_cast_fu_140_p1 = $signed(tmp19_fu_134_p2);

assign tmp19_fu_134_p2 = ($signed(tmp18_fu_128_p2) + $signed(sext_ln21_10_fu_114_p1));

assign tmp1_fu_190_p2 = ($signed(p_read_3_reg_766) + $signed(p_read_2_reg_758));

assign tmp218_fu_194_p2 = (tmp1_fu_190_p2 + tmp_fu_186_p2);

assign tmp25_cast72_fu_293_p1 = $signed(tmp25_fu_287_p2);

assign tmp25_fu_287_p2 = ($signed(sext_ln21_7_fu_167_p1) - $signed(sext_ln21_2_fu_155_p1));

assign tmp27_cast_fu_303_p1 = tmp27_fu_297_p2;

assign tmp27_fu_297_p2 = ($signed(sext_ln21_7_fu_167_p1) + $signed(sext_ln21_6_fu_164_p1));

assign tmp28_fu_319_p2 = ($signed(tmp27_cast_fu_303_p1) - $signed(p_shl1_fu_311_p3));

assign tmp35_fu_355_p2 = ($signed(sext_ln21_reg_804) - $signed(sext_ln21_9_fu_173_p1));

assign tmp39_cast_fu_370_p1 = $signed(tmp39_fu_364_p2);

assign tmp39_fu_364_p2 = ($signed(sext_ln21_3_fu_158_p1) - $signed(sext_ln21_2_fu_155_p1));

assign tmp3_fu_200_p3 = {{tmp218_fu_194_p2}, {13'd0}};

assign tmp5716_fu_215_p2 = ($signed(p_read_4_reg_773) + $signed(p_read_5_reg_778));

assign tmp6_fu_219_p3 = {{tmp5716_fu_215_p2}, {13'd0}};

assign tmp7_cast70_fu_264_p1 = $signed(tmp7_fu_258_p2);

assign tmp7_fu_258_p2 = ($signed(sext_ln21_3_fu_158_p1) - $signed(sext_ln21_6_fu_164_p1));

assign tmp_1_fu_208_p3 = {{p_read21_reg_798}, {13'd4096}};

assign tmp_3_fu_233_p2 = (add_ln21_fu_227_p2 + tmp6_fu_219_p3);

assign tmp_fu_186_p2 = ($signed(p_read_6_reg_784) + $signed(p_read_7_reg_791));

assign trunc_ln23_2_fu_449_p1 = grp_fu_657_p4;

assign trunc_ln23_6_fu_496_p1 = grp_fu_713_p4;

endmodule //dct_dct_1d
