# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/divby13_stream/divby13_stream.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream || ORIG_REF_NAME==divby13_stream} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_axi_dma_1/divby13_stream_axi_dma_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_axi_dma_1 || ORIG_REF_NAME==divby13_stream_axi_dma_1} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_axi_mem_intercon_0/divby13_stream_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_axi_mem_intercon_0 || ORIG_REF_NAME==divby13_stream_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_axi_mem_intercon_1_0/divby13_stream_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_axi_mem_intercon_1_0 || ORIG_REF_NAME==divby13_stream_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_zynq_ultra_ps_e_0_1/divby13_stream_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==divby13_stream_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_xbar_3/divby13_stream_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_xbar_3 || ORIG_REF_NAME==divby13_stream_xbar_3} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_ps7_0_axi_periph_0/divby13_stream_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_ps7_0_axi_periph_0 || ORIG_REF_NAME==divby13_stream_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_rst_ps7_0_100M_0/divby13_stream_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_rst_ps7_0_100M_0 || ORIG_REF_NAME==divby13_stream_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_auto_us_0/divby13_stream_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_auto_us_0 || ORIG_REF_NAME==divby13_stream_auto_us_0} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_auto_ds_0/divby13_stream_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_auto_ds_0 || ORIG_REF_NAME==divby13_stream_auto_ds_0} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_auto_pc_0/divby13_stream_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_auto_pc_0 || ORIG_REF_NAME==divby13_stream_auto_pc_0} -quiet] -quiet

# IP: bd/divby13_stream/ip/divby13_stream_divby13_stream_0_2/divby13_stream_divby13_stream_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_stream_divby13_stream_0_2 || ORIG_REF_NAME==divby13_stream_divby13_stream_0_2} -quiet] -quiet

# XDC: c:/GitRepos/EECE4632/HW4/Vivado/divby13_stream/divby13_stream.gen/sources_1/bd/divby13_stream/divby13_stream_ooc.xdc
