-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct_dct_1d is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of dct_dct_1d is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv29_25A1 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000010010110100001";
    constant ap_const_lv29_1FFFD39E : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111101001110011110";
    constant ap_const_lv29_1FFFDA60 : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111101101001100000";
    constant ap_const_lv29_2C63 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000010110001100011";
    constant ap_const_lv29_8D4 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000100011010100";
    constant ap_const_lv29_29CF : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000010100111001111";
    constant ap_const_lv29_1000 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000001000000000000";
    constant ap_const_lv29_1924 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000001100100100100";
    constant ap_const_lv29_1151 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000001000101010001";

attribute shreg_extract : string;
    signal p_read_1_reg_751 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_read_2_reg_758 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_2_reg_758_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_2_reg_758_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_3_reg_766 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_4_reg_773 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_5_reg_778 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_5_reg_778_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_6_reg_784 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_7_reg_791 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read21_reg_798 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln21_fu_98_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln21_reg_804 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp19_cast_fu_140_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_15_fu_144_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_15_reg_815 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_15_reg_815_pp0_iter1_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_15_reg_815_pp0_iter2_reg : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_17_fu_148_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_1_fu_152_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_11_fu_176_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_11_reg_833 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln_reg_839 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_839_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_839_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln21_12_fu_255_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_12_reg_844 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp7_cast70_fu_264_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_14_fu_284_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_14_reg_856 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp25_cast72_fu_293_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln23_4_reg_868 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln23_4_reg_868_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln23_4_reg_868_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln23_fu_360_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln21_fu_380_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln21_3_fu_385_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln21_5_fu_390_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln21_7_fu_398_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln21_11_fu_404_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln21_1_fu_413_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_570_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_580_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_588_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_596_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_16_reg_924 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln21_9_fu_419_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_606_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_614_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln21_13_fu_425_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_622_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_fu_98_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln21_4_fu_102_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln11_fu_106_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln11_1_fu_110_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln21_10_fu_114_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln21_4_fu_102_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp17_fu_118_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp17_cast_fu_124_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln11_fu_106_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp18_fu_128_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln21_10_fu_114_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp19_fu_134_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln21_15_fu_144_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln21_17_fu_148_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp1_fu_190_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_186_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp218_fu_194_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp5716_fu_215_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_208_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal shl_ln_fu_179_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln21_fu_227_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp6_fu_219_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_3_fu_233_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp3_fu_200_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_fu_239_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_3_fu_158_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln21_6_fu_164_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp7_fu_258_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln21_2_fu_155_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp11_fu_268_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp11_cast_fu_274_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln21_5_fu_161_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln21_7_fu_167_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp25_fu_287_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp27_fu_297_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal empty_fu_307_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp27_cast_fu_303_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_shl1_fu_311_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_shl_fu_325_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln23_fu_333_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp28_fu_319_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_4_fu_339_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln21_9_fu_173_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp35_fu_355_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp39_fu_364_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp39_cast_fu_370_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln21_fu_380_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln21_fu_380_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln21_3_fu_385_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln21_3_fu_385_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln21_5_fu_390_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln21_5_fu_390_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln21_7_fu_398_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln21_16_fu_395_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln21_7_fu_398_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln21_11_fu_404_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln21_11_fu_404_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln21_1_fu_413_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln21_13_fu_410_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln21_1_fu_413_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln21_9_fu_419_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln21_9_fu_419_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln21_13_fu_425_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln21_13_fu_425_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln23_12_fu_430_p0 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_639_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_648_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_12_fu_430_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln23_12_fu_430_p2 : signal is "no";
    signal add_ln23_1_fu_434_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_630_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_1_fu_434_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln23_1_fu_434_p2 : signal is "no";
    signal trunc_ln23_2_fu_449_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_657_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_18_fu_458_p0 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_677_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_18_fu_458_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln23_18_fu_458_p2 : signal is "no";
    signal add_ln23_3_fu_462_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_668_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_3_fu_462_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln23_3_fu_462_p2 : signal is "no";
    signal add_ln23_23_fu_477_p0 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_704_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_695_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_23_fu_477_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln23_23_fu_477_p2 : signal is "no";
    signal add_ln23_5_fu_481_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_686_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_5_fu_481_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln23_5_fu_481_p2 : signal is "no";
    signal trunc_ln23_6_fu_496_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_713_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_29_fu_505_p0 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_742_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_733_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_29_fu_505_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln23_29_fu_505_p2 : signal is "no";
    signal add_ln23_7_fu_509_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_724_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln23_7_fu_509_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln23_7_fu_509_p2 : signal is "no";
    signal grp_fu_570_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_570_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln11_1_fu_110_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_570_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_580_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_580_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_580_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_588_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_596_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_596_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_596_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_606_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_606_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_614_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_614_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_614_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_622_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_622_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_630_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_630_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_639_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_639_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_648_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_648_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_657_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_657_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln21_8_fu_170_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_657_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_668_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_668_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_677_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_677_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_677_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_686_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_695_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_695_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_704_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_704_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_704_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_713_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_713_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_713_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_724_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_733_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_733_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_742_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_742_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_742_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_570_ce : STD_LOGIC;
    signal grp_fu_580_ce : STD_LOGIC;
    signal grp_fu_588_ce : STD_LOGIC;
    signal grp_fu_596_ce : STD_LOGIC;
    signal grp_fu_606_ce : STD_LOGIC;
    signal grp_fu_614_ce : STD_LOGIC;
    signal grp_fu_622_ce : STD_LOGIC;
    signal grp_fu_630_ce : STD_LOGIC;
    signal grp_fu_639_ce : STD_LOGIC;
    signal grp_fu_648_ce : STD_LOGIC;
    signal grp_fu_657_ce : STD_LOGIC;
    signal grp_fu_668_ce : STD_LOGIC;
    signal grp_fu_677_ce : STD_LOGIC;
    signal grp_fu_686_ce : STD_LOGIC;
    signal grp_fu_695_ce : STD_LOGIC;
    signal grp_fu_704_ce : STD_LOGIC;
    signal grp_fu_713_ce : STD_LOGIC;
    signal grp_fu_724_ce : STD_LOGIC;
    signal grp_fu_733_ce : STD_LOGIC;
    signal grp_fu_742_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal p_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read1_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read2_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read3_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read4_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read5_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read6_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read7_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_3_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_4_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_5_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_6_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_7_int_reg : STD_LOGIC_VECTOR (15 downto 0);

    component dct_mul_16s_15ns_29_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mul_16s_15s_29_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_ama_submuladd_16s_16s_12ns_29s_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (11 downto 0);
        din3 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_18s_14ns_13ns_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_14ns_29s_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_ama_submuladd_16s_16s_13ns_29s_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        din3 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_15s_29s_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_18s_13ns_13ns_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_14ns_29ns_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_15s_13ns_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_17s_13ns_29s_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_ama_addmuladd_18s_16s_13ns_29ns_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        din3 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_17s_12ns_13ns_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_15s_29ns_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_17s_12ns_29s_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_17s_13ns_13ns_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_ama_submuladd_18s_16s_14ns_29ns_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (13 downto 0);
        din3 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;



begin
    mul_16s_15ns_29_1_0_U11 : component dct_mul_16s_15ns_29_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln21_fu_380_p0,
        din1 => mul_ln21_fu_380_p1,
        dout => mul_ln21_fu_380_p2);

    mul_16s_15s_29_1_0_U12 : component dct_mul_16s_15s_29_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln21_3_fu_385_p0,
        din1 => mul_ln21_3_fu_385_p1,
        dout => mul_ln21_3_fu_385_p2);

    mul_16s_15s_29_1_0_U13 : component dct_mul_16s_15s_29_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln21_5_fu_390_p0,
        din1 => mul_ln21_5_fu_390_p1,
        dout => mul_ln21_5_fu_390_p2);

    mul_16s_15ns_29_1_0_U14 : component dct_mul_16s_15ns_29_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln21_7_fu_398_p0,
        din1 => mul_ln21_7_fu_398_p1,
        dout => mul_ln21_7_fu_398_p2);

    mul_16s_15s_29_1_0_U15 : component dct_mul_16s_15s_29_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln21_11_fu_404_p0,
        din1 => mul_ln21_11_fu_404_p1,
        dout => mul_ln21_11_fu_404_p2);

    mul_16s_15s_29_1_0_U16 : component dct_mul_16s_15s_29_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln21_1_fu_413_p0,
        din1 => mul_ln21_1_fu_413_p1,
        dout => mul_ln21_1_fu_413_p2);

    mul_16s_15ns_29_1_0_U17 : component dct_mul_16s_15ns_29_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln21_9_fu_419_p0,
        din1 => mul_ln21_9_fu_419_p1,
        dout => mul_ln21_9_fu_419_p2);

    mul_16s_15s_29_1_0_U18 : component dct_mul_16s_15s_29_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln21_13_fu_425_p0,
        din1 => mul_ln21_13_fu_425_p1,
        dout => mul_ln21_13_fu_425_p2);

    ama_submuladd_16s_16s_12ns_29s_29_4_0_U19 : component dct_ama_submuladd_16s_16s_12ns_29s_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 12,
        din3_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_570_p0,
        din1 => grp_fu_570_p1,
        din2 => grp_fu_570_p2,
        din3 => mul_ln21_fu_380_p2,
        ce => grp_fu_570_ce,
        dout => grp_fu_570_p4);

    mac_muladd_18s_14ns_13ns_29_4_0_U20 : component dct_mac_muladd_18s_14ns_13ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 14,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_580_p0,
        din1 => grp_fu_580_p1,
        din2 => grp_fu_580_p2,
        ce => grp_fu_580_ce,
        dout => grp_fu_580_p3);

    mac_muladd_16s_14ns_29s_29_4_0_U21 : component dct_mac_muladd_16s_14ns_29s_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read5_int_reg,
        din1 => grp_fu_588_p1,
        din2 => mul_ln21_3_fu_385_p2,
        ce => grp_fu_588_ce,
        dout => grp_fu_588_p3);

    ama_submuladd_16s_16s_13ns_29s_29_4_0_U22 : component dct_ama_submuladd_16s_16s_13ns_29s_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 13,
        din3_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_596_p0,
        din1 => grp_fu_596_p1,
        din2 => grp_fu_596_p2,
        din3 => mul_ln21_5_fu_390_p2,
        ce => grp_fu_596_ce,
        dout => grp_fu_596_p4);

    mac_muladd_16s_15s_29s_29_4_0_U23 : component dct_mac_muladd_16s_15s_29s_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_606_p0,
        din1 => grp_fu_606_p1,
        din2 => mul_ln21_7_fu_398_p2,
        ce => grp_fu_606_ce,
        dout => grp_fu_606_p3);

    mac_muladd_18s_13ns_13ns_29_4_0_U24 : component dct_mac_muladd_18s_13ns_13ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 13,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_614_p0,
        din1 => grp_fu_614_p1,
        din2 => grp_fu_614_p2,
        ce => grp_fu_614_ce,
        dout => grp_fu_614_p3);

    mac_muladd_16s_14ns_29s_29_4_0_U25 : component dct_mac_muladd_16s_14ns_29s_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_622_p0,
        din1 => grp_fu_622_p1,
        din2 => mul_ln21_11_fu_404_p2,
        ce => grp_fu_622_ce,
        dout => grp_fu_622_p3);

    mac_muladd_16s_14ns_29ns_29_4_0_U26 : component dct_mac_muladd_16s_14ns_29ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_630_p0,
        din1 => grp_fu_630_p1,
        din2 => grp_fu_570_p4,
        ce => grp_fu_630_ce,
        dout => grp_fu_630_p3);

    mac_muladd_16s_15s_13ns_29_4_0_U27 : component dct_mac_muladd_16s_15s_13ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read_1_reg_751,
        din1 => grp_fu_639_p1,
        din2 => grp_fu_639_p2,
        ce => grp_fu_639_ce,
        dout => grp_fu_639_p3);

    mac_muladd_17s_13ns_29s_29_4_0_U28 : component dct_mac_muladd_17s_13ns_29s_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 13,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_648_p0,
        din1 => grp_fu_648_p1,
        din2 => mul_ln21_1_fu_413_p2,
        ce => grp_fu_648_ce,
        dout => grp_fu_648_p3);

    ama_addmuladd_18s_16s_13ns_29ns_29_4_0_U29 : component dct_ama_addmuladd_18s_16s_13ns_29ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        din2_WIDTH => 13,
        din3_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_657_p0,
        din1 => grp_fu_657_p1,
        din2 => grp_fu_657_p2,
        din3 => grp_fu_580_p3,
        ce => grp_fu_657_ce,
        dout => grp_fu_657_p4);

    mac_muladd_16s_14ns_29ns_29_4_0_U30 : component dct_mac_muladd_16s_14ns_29ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_668_p0,
        din1 => grp_fu_668_p1,
        din2 => grp_fu_588_p3,
        ce => grp_fu_668_ce,
        dout => grp_fu_668_p3);

    mac_muladd_17s_12ns_13ns_29_4_0_U31 : component dct_mac_muladd_17s_12ns_13ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 12,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_677_p0,
        din1 => grp_fu_677_p1,
        din2 => grp_fu_677_p2,
        ce => grp_fu_677_ce,
        dout => grp_fu_677_p3);

    mac_muladd_16s_15s_29ns_29_4_0_U32 : component dct_mac_muladd_16s_15s_29ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read_7_reg_791,
        din1 => grp_fu_686_p1,
        din2 => grp_fu_606_p3,
        ce => grp_fu_686_ce,
        dout => grp_fu_686_p3);

    mac_muladd_17s_12ns_29s_29_4_0_U33 : component dct_mac_muladd_17s_12ns_29s_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 12,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_695_p0,
        din1 => grp_fu_695_p1,
        din2 => mul_ln21_9_fu_419_p2,
        ce => grp_fu_695_ce,
        dout => grp_fu_695_p3);

    mac_muladd_17s_13ns_13ns_29_4_0_U34 : component dct_mac_muladd_17s_13ns_13ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 13,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_704_p0,
        din1 => grp_fu_704_p1,
        din2 => grp_fu_704_p2,
        ce => grp_fu_704_ce,
        dout => grp_fu_704_p3);

    ama_submuladd_18s_16s_14ns_29ns_29_4_0_U35 : component dct_ama_submuladd_18s_16s_14ns_29ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        din2_WIDTH => 14,
        din3_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_713_p0,
        din1 => grp_fu_713_p1,
        din2 => grp_fu_713_p2,
        din3 => grp_fu_614_p3,
        ce => grp_fu_713_ce,
        dout => grp_fu_713_p4);

    mac_muladd_16s_14ns_29ns_29_4_0_U36 : component dct_mac_muladd_16s_14ns_29ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read_6_reg_784,
        din1 => grp_fu_724_p1,
        din2 => grp_fu_622_p3,
        ce => grp_fu_724_ce,
        dout => grp_fu_724_p3);

    mac_muladd_17s_13ns_29s_29_4_0_U37 : component dct_mac_muladd_17s_13ns_29s_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 13,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_733_p0,
        din1 => grp_fu_733_p1,
        din2 => mul_ln21_13_fu_425_p2,
        ce => grp_fu_733_ce,
        dout => grp_fu_733_p3);

    mac_muladd_17s_12ns_13ns_29_4_0_U38 : component dct_mac_muladd_17s_12ns_13ns_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 12,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_742_p0,
        din1 => grp_fu_742_p1,
        din2 => grp_fu_742_p2,
        ce => grp_fu_742_ce,
        dout => grp_fu_742_p3);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                add_ln23_16_reg_924 <= grp_fu_596_p4;
                p_read21_reg_798 <= p_read_int_reg;
                p_read_1_reg_751 <= p_read7_int_reg;
                p_read_2_reg_758 <= p_read6_int_reg;
                p_read_2_reg_758_pp0_iter1_reg <= p_read_2_reg_758;
                p_read_2_reg_758_pp0_iter2_reg <= p_read_2_reg_758_pp0_iter1_reg;
                p_read_3_reg_766 <= p_read5_int_reg;
                p_read_4_reg_773 <= p_read4_int_reg;
                p_read_5_reg_778 <= p_read3_int_reg;
                p_read_5_reg_778_pp0_iter1_reg <= p_read_5_reg_778;
                p_read_6_reg_784 <= p_read2_int_reg;
                p_read_7_reg_791 <= p_read1_int_reg;
                sext_ln21_11_reg_833 <= sext_ln21_11_fu_176_p1;
                sext_ln21_12_reg_844 <= sext_ln21_12_fu_255_p1;
                sext_ln21_14_reg_856 <= sext_ln21_14_fu_284_p1;
                sext_ln21_15_reg_815 <= sext_ln21_15_fu_144_p1;
                sext_ln21_15_reg_815_pp0_iter1_reg <= sext_ln21_15_reg_815;
                sext_ln21_15_reg_815_pp0_iter2_reg <= sext_ln21_15_reg_815_pp0_iter1_reg;
                sext_ln21_reg_804 <= sext_ln21_fu_98_p1;
                trunc_ln23_4_reg_868 <= add_ln23_4_fu_339_p2(28 downto 13);
                trunc_ln23_4_reg_868_pp0_iter2_reg <= trunc_ln23_4_reg_868;
                trunc_ln23_4_reg_868_pp0_iter3_reg <= trunc_ln23_4_reg_868_pp0_iter2_reg;
                trunc_ln_reg_839 <= add_ln23_fu_239_p2(28 downto 13);
                trunc_ln_reg_839_pp0_iter2_reg <= trunc_ln_reg_839;
                trunc_ln_reg_839_pp0_iter3_reg <= trunc_ln_reg_839_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= trunc_ln_reg_839_pp0_iter3_reg;
                ap_return_1_int_reg <= add_ln23_1_fu_434_p2(28 downto 13);
                ap_return_2_int_reg <= trunc_ln23_2_fu_449_p1(28 downto 13);
                ap_return_3_int_reg <= add_ln23_3_fu_462_p2(28 downto 13);
                ap_return_4_int_reg <= trunc_ln23_4_reg_868_pp0_iter3_reg;
                ap_return_5_int_reg <= add_ln23_5_fu_481_p2(28 downto 13);
                ap_return_6_int_reg <= trunc_ln23_6_fu_496_p1(28 downto 13);
                ap_return_7_int_reg <= add_ln23_7_fu_509_p2(28 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                p_read1_int_reg <= p_read1;
                p_read2_int_reg <= p_read2;
                p_read3_int_reg <= p_read3;
                p_read4_int_reg <= p_read4;
                p_read5_int_reg <= p_read5;
                p_read6_int_reg <= p_read6;
                p_read7_int_reg <= p_read7;
                p_read_int_reg <= p_read;
            end if;
        end if;
    end process;
    add_ln21_fu_227_p2 <= std_logic_vector(unsigned(tmp_1_fu_208_p3) + unsigned(shl_ln_fu_179_p3));
    add_ln23_12_fu_430_p0 <= grp_fu_639_p3;
    add_ln23_12_fu_430_p2 <= std_logic_vector(signed(add_ln23_12_fu_430_p0) + signed(grp_fu_648_p3));
    add_ln23_18_fu_458_p0 <= grp_fu_677_p3;
    add_ln23_18_fu_458_p2 <= std_logic_vector(signed(add_ln23_18_fu_458_p0) + signed(add_ln23_16_reg_924));
    add_ln23_1_fu_434_p1 <= grp_fu_630_p3;
    add_ln23_1_fu_434_p2 <= std_logic_vector(unsigned(add_ln23_12_fu_430_p2) + unsigned(add_ln23_1_fu_434_p1));
    add_ln23_23_fu_477_p0 <= grp_fu_704_p3;
    add_ln23_23_fu_477_p2 <= std_logic_vector(signed(add_ln23_23_fu_477_p0) + signed(grp_fu_695_p3));
    add_ln23_29_fu_505_p0 <= grp_fu_742_p3;
    add_ln23_29_fu_505_p2 <= std_logic_vector(signed(add_ln23_29_fu_505_p0) + signed(grp_fu_733_p3));
    add_ln23_3_fu_462_p1 <= grp_fu_668_p3;
    add_ln23_3_fu_462_p2 <= std_logic_vector(unsigned(add_ln23_18_fu_458_p2) + unsigned(add_ln23_3_fu_462_p1));
    add_ln23_4_fu_339_p2 <= std_logic_vector(unsigned(sub_ln23_fu_333_p2) + unsigned(tmp28_fu_319_p2));
    add_ln23_5_fu_481_p1 <= grp_fu_686_p3;
    add_ln23_5_fu_481_p2 <= std_logic_vector(unsigned(add_ln23_23_fu_477_p2) + unsigned(add_ln23_5_fu_481_p1));
    add_ln23_7_fu_509_p1 <= grp_fu_724_p3;
    add_ln23_7_fu_509_p2 <= std_logic_vector(unsigned(add_ln23_29_fu_505_p2) + unsigned(add_ln23_7_fu_509_p1));
    add_ln23_fu_239_p2 <= std_logic_vector(unsigned(tmp_3_fu_233_p2) + unsigned(tmp3_fu_200_p3));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(trunc_ln_reg_839_pp0_iter3_reg, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= trunc_ln_reg_839_pp0_iter3_reg;
        else 
            ap_return_0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(add_ln23_1_fu_434_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= add_ln23_1_fu_434_p2(28 downto 13);
        else 
            ap_return_1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(trunc_ln23_2_fu_449_p1, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= trunc_ln23_2_fu_449_p1(28 downto 13);
        else 
            ap_return_2 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_3_assign_proc : process(add_ln23_3_fu_462_p2, ap_ce_reg, ap_return_3_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_3 <= ap_return_3_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_3 <= add_ln23_3_fu_462_p2(28 downto 13);
        else 
            ap_return_3 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_4_assign_proc : process(trunc_ln23_4_reg_868_pp0_iter3_reg, ap_ce_reg, ap_return_4_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_4 <= ap_return_4_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_4 <= trunc_ln23_4_reg_868_pp0_iter3_reg;
        else 
            ap_return_4 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_5_assign_proc : process(add_ln23_5_fu_481_p2, ap_ce_reg, ap_return_5_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_5 <= ap_return_5_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_5 <= add_ln23_5_fu_481_p2(28 downto 13);
        else 
            ap_return_5 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_6_assign_proc : process(trunc_ln23_6_fu_496_p1, ap_ce_reg, ap_return_6_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_6 <= ap_return_6_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_6 <= trunc_ln23_6_fu_496_p1(28 downto 13);
        else 
            ap_return_6 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_7_assign_proc : process(add_ln23_7_fu_509_p2, ap_ce_reg, ap_return_7_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_7 <= ap_return_7_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_7 <= add_ln23_7_fu_509_p2(28 downto 13);
        else 
            ap_return_7 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    empty_fu_307_p1 <= tmp27_fu_297_p2(16 - 1 downto 0);

    grp_fu_570_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_570_ce <= ap_const_logic_1;
        else 
            grp_fu_570_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_570_p0 <= sext_ln21_4_fu_102_p1(16 - 1 downto 0);
    grp_fu_570_p1 <= sext_ln11_1_fu_110_p1(16 - 1 downto 0);
    grp_fu_570_p2 <= ap_const_lv29_8D4(12 - 1 downto 0);

    grp_fu_580_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_580_ce <= ap_const_logic_1;
        else 
            grp_fu_580_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_580_p0 <= tmp19_cast_fu_140_p1(18 - 1 downto 0);
    grp_fu_580_p1 <= ap_const_lv29_29CF(14 - 1 downto 0);
    grp_fu_580_p2 <= ap_const_lv29_1000(13 - 1 downto 0);

    grp_fu_588_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_588_ce <= ap_const_logic_1;
        else 
            grp_fu_588_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_588_p1 <= ap_const_lv29_2C63(14 - 1 downto 0);

    grp_fu_596_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_596_ce <= ap_const_logic_1;
        else 
            grp_fu_596_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_596_p0 <= sext_ln11_1_fu_110_p1(16 - 1 downto 0);
    grp_fu_596_p1 <= sext_ln21_4_fu_102_p1(16 - 1 downto 0);
    grp_fu_596_p2 <= ap_const_lv29_1924(13 - 1 downto 0);

    grp_fu_606_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_606_ce <= ap_const_logic_1;
        else 
            grp_fu_606_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_606_p0 <= sext_ln21_17_fu_148_p1(16 - 1 downto 0);
    grp_fu_606_p1 <= ap_const_lv29_1FFFDA60(15 - 1 downto 0);

    grp_fu_614_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_614_ce <= ap_const_logic_1;
        else 
            grp_fu_614_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_614_p0 <= tmp19_cast_fu_140_p1(18 - 1 downto 0);
    grp_fu_614_p1 <= ap_const_lv29_1151(13 - 1 downto 0);
    grp_fu_614_p2 <= ap_const_lv29_1000(13 - 1 downto 0);

    grp_fu_622_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_622_ce <= ap_const_logic_1;
        else 
            grp_fu_622_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_622_p0 <= sext_ln21_17_fu_148_p1(16 - 1 downto 0);
    grp_fu_622_p1 <= ap_const_lv29_2C63(14 - 1 downto 0);

    grp_fu_630_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_630_ce <= ap_const_logic_1;
        else 
            grp_fu_630_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_630_p0 <= sext_ln21_1_fu_152_p1(16 - 1 downto 0);
    grp_fu_630_p1 <= ap_const_lv29_2C63(14 - 1 downto 0);

    grp_fu_639_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_639_ce <= ap_const_logic_1;
        else 
            grp_fu_639_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_639_p1 <= ap_const_lv29_1FFFD39E(15 - 1 downto 0);
    grp_fu_639_p2 <= ap_const_lv29_1000(13 - 1 downto 0);

    grp_fu_648_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_648_ce <= ap_const_logic_1;
        else 
            grp_fu_648_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_648_p0 <= tmp7_cast70_fu_264_p1(17 - 1 downto 0);
    grp_fu_648_p1 <= ap_const_lv29_1924(13 - 1 downto 0);

    grp_fu_657_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_657_ce <= ap_const_logic_1;
        else 
            grp_fu_657_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_657_p0 <= std_logic_vector(signed(tmp11_cast_fu_274_p1) - signed(sext_ln21_5_fu_161_p1));
    grp_fu_657_p1 <= sext_ln21_8_fu_170_p1(16 - 1 downto 0);
    grp_fu_657_p2 <= ap_const_lv29_1151(13 - 1 downto 0);

    grp_fu_668_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_668_ce <= ap_const_logic_1;
        else 
            grp_fu_668_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_668_p0 <= sext_ln21_1_fu_152_p1(16 - 1 downto 0);
    grp_fu_668_p1 <= ap_const_lv29_25A1(14 - 1 downto 0);

    grp_fu_677_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_677_ce <= ap_const_logic_1;
        else 
            grp_fu_677_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_677_p0 <= tmp25_cast72_fu_293_p1(17 - 1 downto 0);
    grp_fu_677_p1 <= ap_const_lv29_8D4(12 - 1 downto 0);
    grp_fu_677_p2 <= ap_const_lv29_1000(13 - 1 downto 0);

    grp_fu_686_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_686_ce <= ap_const_logic_1;
        else 
            grp_fu_686_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_686_p1 <= ap_const_lv29_1FFFD39E(15 - 1 downto 0);

    grp_fu_695_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_695_ce <= ap_const_logic_1;
        else 
            grp_fu_695_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_695_p0 <= tmp7_cast70_fu_264_p1(17 - 1 downto 0);
    grp_fu_695_p1 <= ap_const_lv29_8D4(12 - 1 downto 0);

    grp_fu_704_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_704_ce <= ap_const_logic_1;
        else 
            grp_fu_704_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_704_p0 <= sext_ln23_fu_360_p1(17 - 1 downto 0);
    grp_fu_704_p1 <= ap_const_lv29_1924(13 - 1 downto 0);
    grp_fu_704_p2 <= ap_const_lv29_1000(13 - 1 downto 0);

    grp_fu_713_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_713_ce <= ap_const_logic_1;
        else 
            grp_fu_713_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_713_p0 <= std_logic_vector(signed(tmp39_cast_fu_370_p1) + signed(sext_ln21_5_fu_161_p1));
    grp_fu_713_p1 <= sext_ln21_8_fu_170_p1(16 - 1 downto 0);
    grp_fu_713_p2 <= ap_const_lv29_29CF(14 - 1 downto 0);

    grp_fu_724_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_724_ce <= ap_const_logic_1;
        else 
            grp_fu_724_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_724_p1 <= ap_const_lv29_25A1(14 - 1 downto 0);

    grp_fu_733_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_733_ce <= ap_const_logic_1;
        else 
            grp_fu_733_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_733_p0 <= tmp25_cast72_fu_293_p1(17 - 1 downto 0);
    grp_fu_733_p1 <= ap_const_lv29_1924(13 - 1 downto 0);

    grp_fu_742_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_742_ce <= ap_const_logic_1;
        else 
            grp_fu_742_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_742_p0 <= sext_ln23_fu_360_p1(17 - 1 downto 0);
    grp_fu_742_p1 <= ap_const_lv29_8D4(12 - 1 downto 0);
    grp_fu_742_p2 <= ap_const_lv29_1000(13 - 1 downto 0);
    mul_ln21_11_fu_404_p0 <= sext_ln21_16_fu_395_p1(16 - 1 downto 0);
    mul_ln21_11_fu_404_p1 <= ap_const_lv29_1FFFD39E(15 - 1 downto 0);
    mul_ln21_13_fu_425_p0 <= sext_ln21_15_reg_815_pp0_iter2_reg(16 - 1 downto 0);
    mul_ln21_13_fu_425_p1 <= ap_const_lv29_1FFFDA60(15 - 1 downto 0);
    mul_ln21_1_fu_413_p0 <= sext_ln21_13_fu_410_p1(16 - 1 downto 0);
    mul_ln21_1_fu_413_p1 <= ap_const_lv29_1FFFDA60(15 - 1 downto 0);
    mul_ln21_3_fu_385_p0 <= sext_ln21_14_reg_856(16 - 1 downto 0);
    mul_ln21_3_fu_385_p1 <= ap_const_lv29_1FFFD39E(15 - 1 downto 0);
    mul_ln21_5_fu_390_p0 <= sext_ln21_11_reg_833(16 - 1 downto 0);
    mul_ln21_5_fu_390_p1 <= ap_const_lv29_1FFFDA60(15 - 1 downto 0);
    mul_ln21_7_fu_398_p0 <= sext_ln21_16_fu_395_p1(16 - 1 downto 0);
    mul_ln21_7_fu_398_p1 <= ap_const_lv29_25A1(15 - 1 downto 0);
    mul_ln21_9_fu_419_p0 <= sext_ln21_13_fu_410_p1(16 - 1 downto 0);
    mul_ln21_9_fu_419_p1 <= ap_const_lv29_2C63(15 - 1 downto 0);
    mul_ln21_fu_380_p0 <= sext_ln21_12_reg_844(16 - 1 downto 0);
    mul_ln21_fu_380_p1 <= ap_const_lv29_25A1(15 - 1 downto 0);
    p_shl1_fu_311_p3 <= (empty_fu_307_p1 & ap_const_lv13_0);
    p_shl_fu_325_p3 <= (tmp_fu_186_p2 & ap_const_lv13_0);
    sext_ln11_1_fu_110_p0 <= p_read4_int_reg;
        sext_ln11_1_fu_110_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln11_1_fu_110_p0),17));

    sext_ln11_fu_106_p0 <= p_read4_int_reg;
        sext_ln11_fu_106_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln11_fu_106_p0),18));

    sext_ln21_10_fu_114_p0 <= p_read7_int_reg;
        sext_ln21_10_fu_114_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln21_10_fu_114_p0),18));

        sext_ln21_11_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_1_reg_751),29));

        sext_ln21_12_fu_255_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_7_reg_791),29));

        sext_ln21_13_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_2_reg_758_pp0_iter2_reg),29));

        sext_ln21_14_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_6_reg_784),29));

    sext_ln21_15_fu_144_p0 <= p_read5_int_reg;
        sext_ln21_15_fu_144_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln21_15_fu_144_p0),29));

        sext_ln21_16_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_5_reg_778_pp0_iter1_reg),29));

    sext_ln21_17_fu_148_p0 <= p_read4_int_reg;
        sext_ln21_17_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln21_17_fu_148_p0),29));

        sext_ln21_1_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read21_reg_798),29));

        sext_ln21_2_fu_155_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_7_reg_791),17));

        sext_ln21_3_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_6_reg_784),17));

    sext_ln21_4_fu_102_p0 <= p_read3_int_reg;
        sext_ln21_4_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln21_4_fu_102_p0),17));

        sext_ln21_5_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_3_reg_766),18));

        sext_ln21_6_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_3_reg_766),17));

        sext_ln21_7_fu_167_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_2_reg_758),17));

        sext_ln21_8_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_2_reg_758),18));

        sext_ln21_9_fu_173_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_1_reg_751),17));

    sext_ln21_fu_98_p0 <= p_read_int_reg;
        sext_ln21_fu_98_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln21_fu_98_p0),17));

        sext_ln23_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp35_fu_355_p2),29));

    shl_ln_fu_179_p3 <= (p_read_1_reg_751 & ap_const_lv13_0);
    sub_ln23_fu_333_p2 <= std_logic_vector(unsigned(tmp_3_fu_233_p2) - unsigned(p_shl_fu_325_p3));
        tmp11_cast_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp11_fu_268_p2),18));

    tmp11_fu_268_p2 <= std_logic_vector(signed(sext_ln21_2_fu_155_p1) - signed(sext_ln21_3_fu_158_p1));
        tmp17_cast_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp17_fu_118_p2),18));

    tmp17_fu_118_p2 <= std_logic_vector(signed(sext_ln21_fu_98_p1) - signed(sext_ln21_4_fu_102_p1));
    tmp18_fu_128_p2 <= std_logic_vector(signed(tmp17_cast_fu_124_p1) - signed(sext_ln11_fu_106_p1));
        tmp19_cast_fu_140_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp19_fu_134_p2),29));

    tmp19_fu_134_p2 <= std_logic_vector(unsigned(tmp18_fu_128_p2) + unsigned(sext_ln21_10_fu_114_p1));
    tmp1_fu_190_p2 <= std_logic_vector(signed(p_read_3_reg_766) + signed(p_read_2_reg_758));
    tmp218_fu_194_p2 <= std_logic_vector(unsigned(tmp1_fu_190_p2) + unsigned(tmp_fu_186_p2));
        tmp25_cast72_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp25_fu_287_p2),29));

    tmp25_fu_287_p2 <= std_logic_vector(signed(sext_ln21_7_fu_167_p1) - signed(sext_ln21_2_fu_155_p1));
        tmp27_cast_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp27_fu_297_p2),29));

    tmp27_fu_297_p2 <= std_logic_vector(signed(sext_ln21_7_fu_167_p1) + signed(sext_ln21_6_fu_164_p1));
    tmp28_fu_319_p2 <= std_logic_vector(signed(tmp27_cast_fu_303_p1) - signed(p_shl1_fu_311_p3));
    tmp35_fu_355_p2 <= std_logic_vector(signed(sext_ln21_reg_804) - signed(sext_ln21_9_fu_173_p1));
        tmp39_cast_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp39_fu_364_p2),18));

    tmp39_fu_364_p2 <= std_logic_vector(signed(sext_ln21_3_fu_158_p1) - signed(sext_ln21_2_fu_155_p1));
    tmp3_fu_200_p3 <= (tmp218_fu_194_p2 & ap_const_lv13_0);
    tmp5716_fu_215_p2 <= std_logic_vector(signed(p_read_4_reg_773) + signed(p_read_5_reg_778));
    tmp6_fu_219_p3 <= (tmp5716_fu_215_p2 & ap_const_lv13_0);
        tmp7_cast70_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp7_fu_258_p2),29));

    tmp7_fu_258_p2 <= std_logic_vector(signed(sext_ln21_3_fu_158_p1) - signed(sext_ln21_6_fu_164_p1));
    tmp_1_fu_208_p3 <= (p_read21_reg_798 & ap_const_lv13_1000);
    tmp_3_fu_233_p2 <= std_logic_vector(unsigned(add_ln21_fu_227_p2) + unsigned(tmp6_fu_219_p3));
    tmp_fu_186_p2 <= std_logic_vector(signed(p_read_6_reg_784) + signed(p_read_7_reg_791));
    trunc_ln23_2_fu_449_p1 <= grp_fu_657_p4;
    trunc_ln23_6_fu_496_p1 <= grp_fu_713_p4;
end behav;
