# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/block_1/block_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1 || ORIG_REF_NAME==block_1} -quiet] -quiet

# IP: bd/block_1/ip/block_1_zynq_ultra_ps_e_0_0/block_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==block_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/block_1/ip/block_1_proc_sys_reset_0_0/block_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_proc_sys_reset_0_0 || ORIG_REF_NAME==block_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/block_1/ip/block_1_add_0_0/block_1_add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_add_0_0 || ORIG_REF_NAME==block_1_add_0_0} -quiet] -quiet

# IP: bd/block_1/ip/block_1_auto_pc_0/block_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_auto_pc_0 || ORIG_REF_NAME==block_1_auto_pc_0} -quiet] -quiet

# IP: bd/block_1/ip/block_1_ps8_0_axi_periph_0/block_1_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==block_1_ps8_0_axi_periph_0} -quiet] -quiet

# XDC: c:/Users/tran.timo/lab2/lab2.gen/sources_1/bd/block_1/block_1_ooc.xdc
