# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/divby13/divby13.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13 || ORIG_REF_NAME==divby13} -quiet] -quiet

# IP: bd/divby13/ip/divby13_zynq_ultra_ps_e_0_0/divby13_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==divby13_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/divby13/ip/divby13_proc_sys_reset_0_0/divby13_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_proc_sys_reset_0_0 || ORIG_REF_NAME==divby13_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/divby13/ip/divby13_divby13_0_0/divby13_divby13_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_divby13_0_0 || ORIG_REF_NAME==divby13_divby13_0_0} -quiet] -quiet

# IP: bd/divby13/ip/divby13_auto_pc_0/divby13_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_auto_pc_0 || ORIG_REF_NAME==divby13_auto_pc_0} -quiet] -quiet

# IP: bd/divby13/ip/divby13_ps8_0_axi_periph_0/divby13_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divby13_ps8_0_axi_periph_0 || ORIG_REF_NAME==divby13_ps8_0_axi_periph_0} -quiet] -quiet

# XDC: c:/FPGAHW/HW3/Vivado/divby13/divby13.gen/sources_1/bd/divby13/divby13_ooc.xdc
