# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tran.timo/Documents/ex/vivado/project_1/project_1.srcs/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_zynq_ultra_ps_e_0_0/dma_axis_ip_example_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'dma_axis_ip_example_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tran.timo/Documents/ex/vivado/project_1/project_1.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_zynq_ultra_ps_e_0_0/dma_axis_ip_example_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tran.timo/Documents/ex/vivado/project_1/project_1.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_zynq_ultra_ps_e_0_0/dma_axis_ip_example_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/tran.timo/Documents/ex/vivado/project_1/project_1.srcs/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_zynq_ultra_ps_e_0_0/dma_axis_ip_example_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'dma_axis_ip_example_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tran.timo/Documents/ex/vivado/project_1/project_1.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_zynq_ultra_ps_e_0_0/dma_axis_ip_example_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tran.timo/Documents/ex/vivado/project_1/project_1.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_zynq_ultra_ps_e_0_0/dma_axis_ip_example_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
